[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अच् + र् ह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'यर् ( = हल् - ह्)'
"परिणामः" = 'यरो द्वे वा'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = 'आगमः विकल्पेन पूर्वस्य'
"सूत्रम्" = '''
अचः रहाभ्यां द्वे [पूर्वत्र असिद्धम् संहितायाम् यरः]॥
'''
"उदाहरणम्" = 'धर्मः - धर्म्मः। ब्रह्म्मा।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अच् +  यर्( = हल् - ह्)'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'हल् (=अनच्)'
"परिणामः" = 'यरो द्वे वा'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = 'आगमः विकल्पेन पूर्वस्य'
"सूत्रम्" = '''
अनचि च [पूर्वत्र असिद्धम् संहितायाम् यरः अचः द्वे]
[सर्वत्र शाकल्यस्य (न भवति)।]'''
"उदाहरणम्" = '''
दद्ध्यत्र। मद्ध्वत्र।
 "कृष्ण:" इत्यत्र ऋकारात् परः यर्-वर्णः षकारः अस्ति । तस्मात् परः स्वरः नास्ति, अतः षकारस्य अनेन सूत्रेण विकल्पेन द्वित्वं भवितुं शक्यते । यथा - कृष्ष्ण: ।'''
"अभावोदाहरणम्" = 'अचः इत्येव - स्मितम्। ध्मातम्।'
"विवरणम्" = '"कृष्ष्ण" इत्यत्र पुनः अनचि च 8|4|47 इत्यनेन प्रथम-षकारस्य द्वित्वं कर्तुम् शक्यते वा? एवं कुर्मश्चेत् अनन्तकालयावत् द्वित्त्वमेव भवेत् इति दोष: उद्भवति । अस्य परिहारार्थम् "लक्ष्ये लक्षं सकृदेव प्रवर्तते" अस्याः परिभाषाया: प्रयोगः क्रियते ।'

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यण्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'मय्'
"परिणामः" = 'यरो द्वे वा'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
यणो मयो द्वे भवत इति वक्तव्यम्। (वा)
केचिदत्र यणः इति पञ्चमी, मयः इति षष्ठी इति व्याचक्षते।
[सर्वत्र शाकल्यस्य ।]'''
"उदाहरणम्" = 'उल्क्का, वल्म्मीकः'
"अभावोदाहरणम्" = ''
"विवरणम्" = '''

'''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'मय्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'यण्'
"परिणामः" = 'यणो द्वे वा'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
यणो मयो द्वे भवत इति वक्तव्यम्। (वा)
अपरे तु मयः इति पञ्चमी, यणः इति षष्ठी इति।
[सर्वत्र शाकल्यस्य ।'''
"उदाहरणम्" = 'दध्य्यत्र, मध्व्वत्र'
"अभावोदाहरणम्" = ''
"विवरणम्" = '''

'''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'शर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खय्'
"परिणामः" = 'खयो द्वे वा'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
शरः खयो द्वे भवत इति वक्तव्यम्।  (वा)
 यदि शरः इति पञ्चमी, खयः इति षष्ठी।
[सर्वत्र शाकल्यस्य ।]'''
"उदाहरणम्" = 'स्त्थाली, स्त्थाता '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'खय्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'शर्'
"परिणामः" = 'शरो द्वे वा'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
शरः खयो द्वे भवत इति वक्तव्यम्।  (वा)
[सर्वत्र शाकल्यस्य ।]'''
"उदाहरणम्" = 'वत्स्सः। इक्ष्षुः। क्ष्षीरम्। अप्स्सराः। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'यर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अवसाने'
"परिणामः" = 'शरो द्वे वा'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
अवसाने च यरो द्वे भवत इति वक्तव्यम्। (वा)
[सर्वत्र शाकल्यस्य ।]'''
"उदाहरणम्" = 'वाक्क, वाक्। त्वक्क्, त्वक्। षट्ट्, षट्। तत्त्, तत्। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'चय् = चटतकप'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श्, ष्, स् =शर्'
"परिणामः" = 'छ् ठ् थ् ख् फ्'
"प्रामुख्यम्" = '५'
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = 'चयः द्वितीयाः शरि पौष्करसादेः इति वाच्यम् (वा)'
"उदाहरणम्" = '''
 तत् + सह = तथ् + सह।
वथ्सः। भ्रातृ॑व्यवा॒न् + स्यात् = भ्रातृ॑व्यवा॒न्त् स्यात् (नश्च) = भ्रातृ॑व्यवा॒न् थ्स्यात् ।
न॒स्मिन्ख्ष॒त्रे॑ ।'''
"अभावोदाहरणम्" = ''
"विवरणम्" = '"पौष्करसादि" नाम्न: आचार्यस्य मतेन।'

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'पुत्र+आदिनी'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''

'''
"परिणामः" = 'न यरो द्वे'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'नादिन्याक्रोशे पुत्रस्य ।'
"उदाहरणम्" = 'पुत्रादिनीत्वम् असि पापे।'
"अभावोदाहरणम्" = 'आक्रोशे इति किम्? तत्त्वकथने द्विर्वचनं भवत्येव, पुअत्रानत्ति इति पुत्त्रादिनी। शिशुमारी व्याघ्री। '
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र्|ह्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'शर् +अच्'
"परिणामः" = 'न यरो द्वे'
"प्रामुख्यम्" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'शरोऽचि ।'
"उदाहरणम्" = ' कर्षति। वर्षति। आकर्षः।'
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अच् + यर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'हल्+हल्'
"परिणामः" = 'न यरो द्वे'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'त्रिप्रभृतिषु शाकटायनस्य ।'
"उदाहरणम्" = 'इन्द्रः। चन्द्रः। उष्ट्रः। राष्ट्रम्। भ्राष्ट्रम्। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अच् + यर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = '*'
"परिणामः" = 'न यरो द्वे'
"प्रामुख्यम्" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सर्वत्र शाकल्यस्य ।'
"उदाहरणम्" = 'अर्कः। मर्कः। ब्रहमा। अपह्नुते। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'दीर्घः + यर्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अनच्परो हल्'
"परिणामः" = 'न यरो द्वे'
"प्रामुख्यम्" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'दीर्घादाचार्याणाम् ।'
"उदाहरणम्" = 'दात्रम्। पात्रम्। मूत्रम्। सूत्रम्। '
"अभावोदाहरणम्" = ''
"विवरणम्" = ''
