[[data]]
"अङ्गम्" = '''
अनुदात्तेत्-वान्।
ङित्-वान्।
'''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'अनुदात्तङित आत्मनेपदम् ।'
"प्रभावोदाहरणम्" = '''
एधँ_ शीङ्।
यङन्ताः। क्यङन्ताः।'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'भावे |‌कर्मणि'
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'भावकर्म्मणोः ।'
"प्रभावोदाहरणम्" = 'बभूवे। क्रियते। भूयते।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'अन्यजनस्य कार्ये कृते'
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'कर्त्तरि कर्म्मव्यतिहारे ।'
"प्रभावोदाहरणम्" = 'व्यतिलुनते क्षेत्रम्॥ शूद्रस्य योग्यं सस्यादिलवनं ब्राह्मणः करोतीत्यर्थः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'परस्पर-क्रियायाम्'
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'कर्त्तरि कर्म्मव्यतिहारे ।'
"प्रभावोदाहरणम्" = 'संप्रहरन्ते राजानः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'न गतिहिंसार्थेभ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इतरेतरान्योन्योपपदाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'नेर्विशः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'परिव्यवेभ्यः क्रियः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'विपराभ्यां जेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'आङो दोऽनास्यविहरणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'क्रीडोऽनुसम्परिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समवप्रविभ्यः स्थः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रकाशनस्थेयाख्ययोश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उदोऽनूर्द्ध्वकर्मणि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उपान्मन्त्रकरणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अकर्मकाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उद्विभ्यां तपः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'आङो यमहनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समो गम्यृच्छिप्रच्छिस्वरत्यर्तिश्रुविदिभ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'निसमुपविभ्यो ह्वः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'स्पर्द्धायामाङः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'गन्धनावक्षेपणसेवनसाहसिक्यप्रतियत्नप्रकथनोपयोगेषु कृञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अधेः प्रसहने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वेः शब्दकर्म्मणः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अकर्मकाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सम्माननोत्सञ्जनाचार्यकरणज्ञानभृतिविगणनव्ययेषु नियः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'कर्तृस्थे चाशरीरे कर्मणि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वृत्तिसर्गतायनेषु क्रमः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उपपराभ्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'आङ उद्गमने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वेः पादविहरणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रोपाभ्यां समर्थाभ्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अनुपसर्गाद्वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अपह्नवे ज्ञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अकर्मकाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सम्प्रतिभ्यामनाध्याने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'भासनोपसम्भाषाज्ञानयत्नविमत्युपमन्त्रणेषु वदः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'व्यक्तवाचां समुच्चारणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अनोरकर्मकात् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'विभाषा विप्रलापे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अवाद्ग्रः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समः प्रतिज्ञाने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उदश्चरः सकर्मकात् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समस्तृतीयायुक्तात् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दाणश्च सा चेच्चतुर्थ्यर्थे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उपाद्यमः स्वकरणे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'ज्ञा, दृश्, श्रू।'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = 'ज्ञाश्रुस्मृदृशां सनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'नानोर्ज्ञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रत्याङ्भ्यां श्रुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'शदेः शितः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'मृङ् लृङि, लिटि शिति'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = 'म्रियतेर्लुङ्‌लिङोश्च ।'
"प्रभावोदाहरणम्" = 'म्रियते'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'मृङ् -(लृङि, लिटि शिति)'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = 'म्रियतेर्लुङ्‌लिङोश्च ।'
"प्रभावोदाहरणम्" = 'मरिष्यति'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'पूर्ववत् सनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'आम्प्रत्ययवत् कृञोऽनुप्रयोगस्य ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रोपाभ्यां युजेरयज्ञपात्रेषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समः क्ष्णुवः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'भुजोऽनवने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'णेरणौ यत् कर्म णौ चेत् स कर्ताऽनाध्याने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'भीस्म्योर्हेतुभये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'गृधिवञ्च्योः प्रलम्भने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'लियः सम्माननशालिनीकरणयोश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'मिथ्योपपदात् कृञोऽभ्यासे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'स्वरितेत्। ञित्-वान्।'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'स्वरितञितः कर्त्रभिप्राये क्रियाफले ।'
"प्रभावोदाहरणम्" = '''गुहुँ' डुकृञ्'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अपाद्वदः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = '''
धातुः
- आकुस्मीयाः'''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'णिचश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'समुदाङ्भ्यो यमोऽग्रन्थे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अनुपसर्गाज्ज्ञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'कर्त्रभिप्रये क्रियाफले आत्मनेपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'विभाषोपपदेन प्रतीयमाने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'आत्मनेपदीभिन्नम्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'शेषात् कर्तरि परस्मैपदम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अनुपराभ्यां कृञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अभिप्रत्यतिभ्यः क्षिपः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्राद्वहः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'परेर्मृषः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'व्याङ्परिभ्यो रमः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'उपाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'विभाषाऽकर्मकात् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'बुधयुधनशजनेङ्प्रुद्रुस्रुभ्यो णेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'निगरणचलनार्थेभ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अणावकर्मकाच्चित्तवत्कर्तृकात् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'न पादम्याङ्यमाङ्यसपरिमुहरुचिनृतिवदवसः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वा क्यषः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'द्युद्भ्यो लुङि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वृद्भ्यः स्यसनोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'परस्मैपदम्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'लुटि च कॢपः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'आकुस्मीयाः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'आत्मनेपदी'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = 'विशेष इव आचरति = विशेषा + यते (क्यङ्)।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'सुबन्तम्'
"प्रत्ययः/ विवक्षा" = 'ङित्'
"परिणामः" = 'आत्मनेपदी धातुः'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = ''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
