[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'भूते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '२'
"परिणामः" = 'णिनिः'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'करणे यजः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '२'
"परिणामः" = 'णिनिः'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'कर्मणि हनः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ब्रह्मभ्रूणवृत्रेषु क्विप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'बहुलं छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सुकर्मपापमन्त्रपुण्येषु कृञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सोमे सुञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अग्नौ चेः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्विप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'कर्मण्यग्न्याख्यायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इनि'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'कर्मणीनिर्विक्रियः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्वनिप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'दृशेः क्वनिप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्वनिप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'राजनि युधिकृञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'क्वनिप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सहे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'समासे सप्तम्यन्तं + जन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सप्तम्यां जनेर्डः ।'
"प्रभावोदाहरणम्" = 'उपसरे जातः = उपसरजः ।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'समासे पञ्चम्यन्तं + अजातौ जन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पञ्चम्यामजातौ ।'
"प्रभावोदाहरणम्" = 'बुद्धिजः संस्कारजः दुखजः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'संज्ञायाम् उपसर्गः + जन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'उपसर्गे च संज्ञायाम् ।'
"प्रभावोदाहरणम्" = 'मानवीः प्रजाः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'कर्म + अनु  + जन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अनौ कर्मणि ।'
"प्रभावोदाहरणम्" = 'पुमनुजा स्त्र्यमनुजः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'पूर्वप्रयोगानुसारं जन्'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ड'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अन्येष्वपि दृश्यते ।'
"प्रभावोदाहरणम्" = 'न जायते = अजः; द्विर्जातः = द्विजः'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
(भूते| आदिकर्मणि) +
‌भावे|कर्मणि'''
"परिणामः" = 'क्त'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
निष्ठा ।
आदिकर्मणि निष्ठा वक्तव्या।
[तयोरेव कृत्यक्तखलर्थाः [भावे, कर्मणि च]]'''
"प्रभावोदाहरणम्" = ' प्रकृतः कटं देवदत्तः।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
(भूते| आदिकर्मणि) +
‌भावे|कर्मणि'''
"परिणामः" = 'क्तवतु'
"प्रसिद्धिः" = '३'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
निष्ठा ।
आदिकर्मणि निष्ठा वक्तव्या।
[तयोरेव कृत्यक्तखलर्थाः [भावे, कर्मणि च]]'''
"प्रभावोदाहरणम्" = ' प्रकृतवान् कटं देवदत्तः। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''

'''
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'ङ्वनिप्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सुयजोर्ङ्वनिप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अतृन्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'जीर्यतेरतृन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लिट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'छन्दसि लिट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'छन्दसि'
"प्रत्ययः/ विवक्षा" = 'लिट्'
"परिणामः" = 'कानच्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लिटः कानज्वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'छन्दसि'
"प्रत्ययः/ विवक्षा" = 'लिट्'
"परिणामः" = 'क्वसु वा'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'क्वसुश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = '''
क्वसोः कित्करणं ‘अनूषिवान्’ इत्यादीनां सिद्धौ ‘वचिस्वपियजादीनां किति’ (पा॰सू॰ ६.१.१५) इत्यनेन सम्प्रसारणे चरितार्थम्।
'''

[[data]]
"अङ्गम्" = '''
भाषायाम्
सद-वस-श्रु'''
"प्रत्ययः/ विवक्षा" = 'लिट्'
"परिणामः" = 'क्वसु वा'
"प्रसिद्धिः" = '२'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'भाषायां सदवसश्रुवः ।'
"प्रभावोदाहरणम्" = '''
उपसेदिवान् (लिट्-वत् अभ्यासकार्यम् एत्वञ्च। ) कौत्सः पाणिनिम्।
निषेदुषस् तस्य आसनम्। (सम्प्रसारणं विद्वस्-शब्दे यथा।)
अनूषिवान्। उपशुश्रुवान्'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'इण् गतौ, अशू व्याप्तौ, वच परिभाषणे'
"प्रत्ययः/ विवक्षा" = 'लिट्'
"परिणामः" = 'क्वसु वा'
"प्रसिद्धिः" = '१'
"विधिप्रकारः" = ''
"विधिः" = 'निपातनानि'
"सूत्रम्" = 'उपेयिवाननाश्वाननूचानश्च ।'
"प्रभावोदाहरणम्" = '''
उपेयिवान्
अनाश्वान्
अनूचान'''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लुङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लुङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'अनद्यतने भूते।'
"परिणामः" = 'लङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अनद्यतने लङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = '''
भविष्यति।
स्मारणे।'''
"परिणामः" = 'लृँट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '''
अभिज्ञावचने लृट्॥
लृट् शेषे च॥'''
"प्रभावोदाहरणम्" = 'स्मर - पूर्वजन्मनि रामो आसीः। तदा त्वं रावणहत्याम् करिष्यसि समुद्रं तीर्त्वा।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लृट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अभिज्ञावचने लृट् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लृट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'न यदि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लृट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'विभाषा साकाङ्क्षे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = '''
संवादपात्रयोः परोक्षे।
कुड्यकटान्तरितम् | द्व्यहवृत्तं त्र्यहवृत्तं चेति …'''
"परिणामः" = 'लिँट्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'परोक्षे लिट्।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = 'कथंजातीयकं पुनः परोक्षं नाम?। (समाधानभाष्यम्) केचित्तावदाहुः ‐ -वर्षशतवृत्तं परोक्षमिति।। अपर आहुः ‐ -वर्षसहस्रवृत्तं परोक्षमिति।। अपर आहुः ‐ ‐ कुड्यकटान्तरितं परोक्षमिति।। अपर आहुः ‐ ‐ -द्व्यहवृत्तं त्र्यहवृत्तं चेति।।'

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'सुप्तमत्तयोरुत्तमे'
"परिणामः" = 'लिँट्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सुप्तमत्तयोरुत्तम इति वक्तव्यम्।'
"प्रभावोदाहरणम्" = 'सुप्तोहं किल विललाप। मत्तोहं किल विललाप। सुप्तोन्वहं किल विललाप। मत्तोन्वहं किल विललाप।'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'अत्यन्तापह्नवे'
"परिणामः" = 'लिँट्'
"प्रसिद्धिः" = '४'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'परोक्षे लिडत्यन्तापह्नवे च'
"प्रभावोदाहरणम्" = ' नो खण्डिकान् जगाम। नोकलिङ्गाञ्ञ्जगाम। '
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'हशश्वतोर्लङ् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'आसन्नकाले प्रश्ने'
"परिणामः" = 'लङ्, लिँट्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'प्रश्ने चासन्नकाले ।'
"प्रभावोदाहरणम्" = 'अगच्छद् देवदत्तः? जगाम देवदत्तः? अयजद् देवदत्तः? इयाज देवदत्तः?'
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = 'धातुः'
"प्रत्ययः/ विवक्षा" = 'स्म-योगे भूते'
"परिणामः" = 'लट्'
"प्रसिद्धिः" = '५'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'लट् स्मे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'अपरोक्षे च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'ननौ पृष्टप्रतिवचने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लट्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'नन्वोर्विभाषा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'लुङ्'
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'पुरि लुङ् चास्मे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रसिद्धिः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'भूतेऽपि दृश्यन्ते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"अन्यटिप्पनी" = ''
