[[data]]
"समासस्थितिः" = ''
"पूर्वनिपातनम्" = 'उपसर्जनम् पूर्वम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'उपसर्जनं पूर्वम्‌ ।'
"उदाहरण-विग्रहः" = 'दिशयोः मध्यः = दिशा अप'
"समस्तपदम् उदाहरणम्" = 'अपदिशा'
"विवरणम्" = '''
"अव्ययं सुपा" इति सूत्रेण समस्यमाने - 
दिशा + अप इत्येतयोः‌ "अप" उपसर्जनम्।'''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'राजदन्तादिः'
"पूर्वनिपातनम्" = 'उपसर्जनम् परम्'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'राजदन्तादिषु परम्‌ ।'
"उदाहरण-विग्रहः" = 'दन्तानां राजा'
"समस्तपदम् उदाहरणम्" = '''
राजदन्तः।
अग्रेवनम्।'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = ''
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'पूर्वकालस्य परनिपातः। (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'धर्मादिः'
"पूर्वनिपातनम्" = 'उपसर्जनम्  पूर्वम्| परम्'
"अवधानावश्यकता" = ''
"सूत्रम्" = 'धर्मादिषूभयथापि (वा)'
"उदाहरण-विग्रहः" = 'अर्थशब्दौ'
"समस्तपदम् उदाहरणम्" = 'शब्दार्थौ'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = '''
द्वन्द्वे
(परसूत्र-विप्रतिषेध-अभावे)'''
"पूर्वनिपातनम्" = 'घिः पूर्वम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'द्वंद्वे घि ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'हरिश् च हरश् च हरिहरौ।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे अनेकशब्दके'
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'अनेकप्राप्तावेकस्य नियमः, शेषे त्वनियमः। (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'पटुमृदुशुक्लाः वा पटुशुक्लमृदवः। '
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'अजादि ^ अदन्तम् पूर्वम्।'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'अजाद्यदन्तम्‌ ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'ईशकृष्णौ।'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे अनेकशब्दके'
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'बहुष्व् अनियमः (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = '''
अश्वरथेन्द्राः |‌ इन्द्ररथाश्वाः।
इन्द्राश्वरथाः'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'अल्पाच्तरः पूर्वम्'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'अल्पाच्तरम्‌ ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'शिवकेशवौ'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'ऋतुनक्षत्राणामानुपूर्व्येण समाक्षराणाम् (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'लघ्वक्षरम्'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'लघ्वक्षरं पूर्वम् (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'कुशकाशम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'गौरवयुक्तं पूर्वम्'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'अभ्यर्हितं च पूर्वम् (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'तापसपर्वतौ'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'ब्राह्मणादिवर्णाः'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'वर्णानामानुपूर्व्येण (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'ब्राह्मणक्षत्रियविट्शूद्राः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'द्वन्द्वे'
"पूर्वनिपातनम्" = 'ज्येष्ठभ्राता'
"अवधानावश्यकता" = '३'
"सूत्रम्" = 'भ्रातुश्च ज्यायसः (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'युधष्ठिरार्जुनौ'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'बहुव्रीहौ'
"पूर्वनिपातनम्" = 'सप्तम्यन्तं | विशेषणम्'
"अवधानावश्यकता" = '५'
"सूत्रम्" = 'सप्तमीविशेषणे बहुव्रीहौ ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = '''
७ - क्ण्ठेकालः। उरसिलोमा।
विशेषणम् चित्रगुः। शबलगुः। '''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'बहुव्रीहौ'
"पूर्वनिपातनम्" = 'सङ्ख्या | सर्वनाम'
"अवधानावश्यकता" = '४'
"सूत्रम्" = 'सर्वनामसङ्ख्ययोरुपसङ्ख्यानम्। (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = '''
 द्विशुक्लः। द्विकृष्णः।
 द्व्यन्यः। त्र्यन्यः।'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'बहुव्रीहौ'
"पूर्वनिपातनम्" = 'प्रियः (विकल्पेन)'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'वा प्रियस्य पूवनिपातः। (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'गुडप्रियः, प्रियगुडः। '
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = 'बहुव्रीहौ'
"पूर्वनिपातनम्" = 'गड्वादौ सप्तम्यन्तं विकल्पेन'
"अवधानावश्यकता" = '२'
"सूत्रम्" = 'सप्तम्याः पूर्वनिपाते प्रप्ते गड्वादिभ्यः सप्तम्यन्तं परम्। (वा)'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = '''
 गडुकण्ठः। गडुशिराः।
कथं वहेगडुः? प्राप्तस्य चाबाधा व्याख्येया।'''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = ''
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'निष्ठा ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = ''
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'वाऽऽहिताग्न्यादिषु ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समासस्थितिः" = ''
"पूर्वनिपातनम्" = ''
"अवधानावश्यकता" = ''
"सूत्रम्" = 'कडाराः कर्मधराये ।'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''
