[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ढ्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'ढ्'
"परिणामः" = 'लोपः, पूर्वतन-अणः दीर्घः'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'ढलोपः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
ढो ढे लोपः ।
[ ढ्रलोपे पूर्वस्य दीर्घोऽणः॥
सहिवहोः अवर्णस्य ओत्‌ ढलोपे ]'''
"उदाहरणम्" = '''
तृणेह्‌ + धि → हो ढः → तृणेढ्‌ + धि → ष्टुना ष्टुः → तृणेढ्‌ + ढि ।
लिह्‌ + ध्वे → लिढ्‌ + ध्वे →लीढ्वे॥
वह्‌ + ता → वढ्‌ + ता → वढ्‌ + धा → वढ्‌ + ढा → व + ढा → वो + ढा → वोढा'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'अ / आ + य् व्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अश्'
"परिणामः" = '''
विकल्पेन पदान्ते अवर्णपूर्वयोः यवयोः लोपः अशि परे
(तदा न पुनः सन्धिः)'''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = 'लोपः पूर्वस्य विकल्पेन'
"सूत्रम्" = 'लोपः शाकल्यस्य (पदस्य अशि परे) (पूर्वत्रासिद्धम्)।'
"उदाहरणम्" = 'गम्यते इति = गम्यतय् इति = गम्यत इति'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'ओतो गार्ग्यस्य ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'उञि च पदे ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'हलि सर्वेषाम् ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'म्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'हल्'
"परिणामः" = '''
ं
'''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'अनुस्वार'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'मोऽनुस्वारः (८।३।२३) '
"उदाहरणम्" = 'रामं वन्दे।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ' न् म्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'झल्'
"परिणामः" = 'ं'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'नश्चापदान्तस्य झलि ।'
"उदाहरणम्" = 'नम् + स्य + तिप् = नंस्यति'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'मो राजि समः क्वौ ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'हे मपरे वा ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'व/यकारस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'नपरे नः ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ङ्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श्, ष्, स् =शर्'
"परिणामः" = '+‌कुक्|‌खक् वा '
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = '''
ङ्णोः कुक्टुक् शरि ।
(आद्यन्तौ टकितौ)
(चयः द्वितीयाः शरि पौष्करसादेः इति वाच्यम् (वा)	)'''
"उदाहरणम्" = 'प्राङ् + षष्ठः = प्राङ्क्षष्ठः, प्राङ्षष्ठः, प्राङ्ख्षष्ठः ।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ण्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श्, ष्, स् =शर्'
"परिणामः" = ' +‌टुक्|ठुक् वा'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = '''
ङ्णोः कुक्टुक् शरि ।
(आद्यन्तौ टकितौ)
(चयः द्वितीयाः शरि पौष्करसादेः इति वाच्यम् (वा)	)'''
"उदाहरणम्" = ' सुगण् + षष्ठः = सुगण्ट्षष्ठः, सुगण्षष्ठः, सुगण्ठ्षठः ।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = 'डः सि धुट् ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'न्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'स्'
"परिणामः" = 'धुक् वा'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'धुक्'
"विधिः" = ''
"सूत्रम्" = 'नश्च ।'
"उदाहरणम्" = 'भवान् + सीदति -> भवान्ध् सीदति -> भवान्त्सीदति ।'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = 'शि तुक् ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ह्रस्व अच्।'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'ङ् म् ञ् ण् न्'
"परिणामः" = 'ङमुट्'
"प्रामुख्यम्" = '४'
"विधिप्रकारः" = 'कुक् टुक् धुक् तुक् ङमुट्'
"विधिः" = ''
"सूत्रम्" = 'ङमो ह्रस्वादचि ङमुण् नित्यम् (८।३।३२)'
"उदाहरणम्" = '''
कुर्वन्नहम्।
नेह - विस्मृतवानह।'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'उञो वः'
"विधिः" = ''
"सूत्रम्" = 'मय उञो वो वा ।'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ष्॥'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
अश्।
[अच् + मृदुच्यञ्जनम्।]'''
"परिणामः" = 'ड्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'जश्त्व'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'झलां जशोऽन्ते (८।२।३९)'
"उदाहरणम्" = 'षष्+भ्यां = षड्भ्यां'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = '[झय्॥ वर्गीयच्यञ्जनम्॥]'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
अश्।
[अच् + मृदुव्यञ्जनम्।]'''
"परिणामः" = 'मृदुवर्गीयं अल्पप्राणम्॥ = जश्॥'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = 'जश्त्व'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
झलां जशोऽन्ते (८।२।३९)
(संहितायां झलां चर्) खरि च (८।४।५५)'''
"उदाहरणम्" = 'अग्निचित् + अत्र = अग्निचिदत्र'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = '[झय्॥ वर्गीयच्यञ्जनम्॥]'
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = 'जश्/ चर्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = '''
झलां जशोऽन्ते (८।२।३९)
वाऽवसाने (८।४।५६)'''
"उदाहरणम्" = '''
वाच् -- वाक्, वाग्। त्वच् -- त्वक्, त्वग्।
'''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = '''
समस्तपदे विकल्पः नास्ति।
तिप्तस्झिसिप्थस्थमिब्वस्मस्'''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ष्॥'
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = 'ड् /ट्'
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = '''
झलां जशोऽन्ते (८।२।३९)
वाऽवसाने (८।४।५६)'''
"उदाहरणम्" = 'षष् => षट्'
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परिणामः" = ''
"प्रामुख्यम्" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''
