[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'तान्येकवचनद्विवचनबहुवचनान्येकशः ।'
"उदाहरणम्" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'सुपः ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'विभक्तिश्च ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'प्रातिपदिकम्'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '''
अर्थवदधातुरप्रत्ययः प्रातिपदिकम्॥
प्रातिपदिकग्रहणे लिङ्गविशिष्टस्यापि ग्रहणम्॥
कृत्-तद्धित-समासाश्च॥'''
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'वृद्धम्'
"संज्ञा" = 'वृद्धम्'
"अन्तर्भूताः" = '''
स्वरेषु प्रथमः वृद्धिः।
त्यत्-आदि - त्वत् भवत्।
नामधेयाः। '''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'वृद्धिर् यस्याचामादिस्तद् वृद्धम्॥'
"उदाहरणम्" = '''
भारत औषद ऐश्वर्य
त्वत् भवत्
हरिनारायण विश्वास'''
"विवरणम्" = ''

[[data]]
"समूहः" = 'वृद्धम्'
"संज्ञा" = 'वृद्धम्'
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'वा नामधेयस्य (वा)॥'
"उदाहरणम्" = 'देवदत्तीयाः (वृद्धात्छः)। दैवदत्ताः।'
"विवरणम्" = ''

[[data]]
"समूहः" = 'वृद्धम्'
"संज्ञा" = 'वृद्धम्'
"अन्तर्भूताः" = 'गोत्रान्त-समास-पदम्, यत्र गोत्रपदं वृद्धम्'
"प्रमुखता" = '४'
"सूत्रम्" = 'गोत्रान्तादसमस्तवत्प्रत्ययो भवतीति वक्तव्यम्।'
"उदाहरणम्" = 'घृतप्रधनो रौढिः घृतरौढिः। तस्य छात्रा घृतरौढीयाः। ओदनप्रधानः पाणिनिः ओदनपाणिनिः। तस्य छात्रा ओदनपाणिनीयाः। वृद्धाम्भीयाः। वृद्धकाश्यपीयाः।'
"विवरणम्" = ''

[[data]]
"संज्ञा" = 'न वृद्धम्'
"अन्तर्भूताः" = 'जिह्वाकात्य-हरितकाय'
"प्रमुखता" = '१'
"सूत्रम्" = 'जिह्वाकात्यहरितकायवर्जम्। '
"उदाहरणम्" = ''
"अभावोदाहरणम्" = 'जैह्वाकाताः। हारितकाताः।'
"विवरणम्" = ''

[[data]]
"संज्ञा" = 'वृद्धम्'
"अन्तर्भूताः" = 'त्यत् त्वत् मत् भवत् एतत् अदः …'
"प्रमुखता" = '५'
"सूत्रम्" = 'त्यदादीनि च'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = 'त्यदीयम्। तदीयम्। एतदीयम्। इदमीयम्। अदसीयम्। त्वदीयम्। त्वादायनिः। मदीयम्। मादायनिः। भवतीयम्। किमीयम्।'
"विवरणम्" = ''

[[data]]
"संज्ञा" = 'वृद्धम्'
"अन्तर्भूताः" = 'प्राचां सम्बन्धी यो देशस्तदभिधानः एङादिः।'
"प्रमुखता" = '२'
"सूत्रम्" = 'एङ् प्राचां देशे'
"उदाहरणम्" = ' भोजकटीयः। गोनर्दीयः।'
"अभावोदाहरणम्" = 'देवदत्तो नाम बाहीकेषु ग्रामह्, तत्र भवः दैवदत्तः।'
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनामस्थानम्'
"संज्ञा" = ''
"अन्तर्भूताः" = 'नपुंसके जस् / शस्'
"प्रामुख्यम्" = '५'
"परिस्थितिः" = ''
"सूत्रम्" = '''
शि सर्वनामस्थानम् ।
[जस्-शसोः शिः]'''
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनामस्थानम्'
"संज्ञा" = ''
"अन्तर्भूताः" = 'सुँ औ जस् अम् औट्'
"प्रामुख्यम्" = '५'
"परिस्थितिः" = ''
"सूत्रम्" = 'सुडनपुंसकस्य ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'पदम्'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'सुप्तिङन्तं पदम् ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'पदम्'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'नः क्ये ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'पदम्'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'सिति च ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'पदम्'
"संज्ञा" = 'अलौकिकम्'
"अन्तर्भूताः" = 'सुँपि असुटि अभमि'
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '''
स्वादिषु असर्वनामस्थाने॥
[यचि भम्]
स्वादि = 4-1-2 to 5-4-151'''
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'भम्'
"संज्ञा" = ''
"अन्तर्भूताः" = '''
स्वादिष्व् असर्वनामस्थाने य्-अच् परे।
त्-स्-अन्त्यं मतुप्-अर्थ-प्रत्यये परे।'''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '''
यचि भम् (स्वादिष्व् असर्वनामस्थाने)॥
स्वादि = 4-1-2 to 5-4-151
तसौ मत्वर्थे ।'''
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'भम्'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'अयस्मयादीनि च्छन्दसि ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = '''
त्वत् भवत् अस्मत् 
पूर्व अपर अन्य पर एक
'''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'सर्वादीनि सर्वनामानि'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'विभाषा दिक्समासे बहुव्रीहौ ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'न बहुव्रीहौ ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'तृतीयासमासे ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'द्वन्द्वे च ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'विभाषा जसि ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'प्रथमचरमतयाल्पार्धकतिपयनेमाश्च ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'पूर्वपरावरदक्षिणोत्तरापराधराणि'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'स्वमज्ञातिधनाख्यायाम् ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सर्वनाम'
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'अन्तरं बहिर्योगोपसंव्यानयोः ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'सम्बोधने च ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'आमन्त्रितम्'
"संज्ञा" = ''
"अन्तर्भूताः" = 'सम्बोधने प्रथमान्तं पदम्'
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'साऽऽमन्त्रितम्‌ ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'सम्बुद्धिः'
"संज्ञा" = ''
"अन्तर्भूताः" = 'सम्बोधने प्रथमान्तं पदम् एकवचनम्'
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = 'एकवचनं संबुद्धिः ।'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''

[[data]]
"समूहः" = 'नदी'
"संज्ञा" = ''
"अन्तर्भूताः" = '(ई| ऊ) ^ नित्यस्त्री (वृत्त्यन्तेऽपि)'
"प्रामुख्यम्" = '५'
"परिस्थितिः" = ''
"सूत्रम्" = 'यू स्त्र्याख्यौ नदी ।'
"उदाहरणम्" = '''
लक्ष्म्याम्।
अतिलक्ष्मीः ब्राह्मणः।'''
"विवरणम्" = ''

[[data]]
"समूहः" = '- नदी'
"संज्ञा" = ''
"अन्तर्भूताः" = '''
अङ्गम् धात्ववयवः&
(एकाच् - इण्|
अनेकाच् संयोगपूर्वम्) - स्त्री'''
"प्रामुख्यम्" = '२'
"परिस्थितिः" = ' + अच्'
"सूत्रम्" = '''
नेयङुवङ्स्थानावस्त्री ।
[अचि श्नुधातुभ्रुवां य्वोरियङुवङौ ।
एर् अनेकाचो ऽसंयोगपूर्वस्य (यण्)॥
इणो यण् अचि॥]'''
"उदाहरणम्" = '''
श्री + औ → श्रियौ।
श्री + अम् → श्रियम्'''
"विवरणम्" = ''

[[data]]
"समूहः" = 'वा नदी'
"संज्ञा" = ''
"अन्तर्भूताः" = '''
अङ्गम् धात्ववयवः&
(एकाच् - इण्|
अनेकाच् संयोगपूर्वम्) - स्त्री'''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ' + अम्'
"सूत्रम्" = 'वाऽऽमि ।'
"उदाहरणम्" = 'श्री + अम् → श्रियम्'
"विवरणम्" = ''

[[data]]
"समूहः" = 'वा नदी'
"संज्ञा" = ''
"अन्तर्भूताः" = '''
अङ्गम् धात्ववयवः&
(एकाच् - इण्|
अनेकाच् संयोगपूर्वम्) - स्त्री'''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ' + ङित्'
"सूत्रम्" = 'ङिति ह्रस्वश्च ।'
"उदाहरणम्" = 'श्रियाम् श्रीणाम्'
"विवरणम्" = ''

[[data]]
"समूहः" = 'वा नदी'
"संज्ञा" = ''
"अन्तर्भूताः" = 'इ|उ नित्यस्त्री'
"प्रामुख्यम्" = ''
"परिस्थितिः" = '+ ङित्'
"सूत्रम्" = 'ङिति ह्रस्वश्च ।'
"उदाहरणम्" = '''
मत्याम् | मतौ
मतये | मत्यै'''
"विवरणम्" = ''

[[data]]
"समूहः" = 'घि'
"संज्ञा" = ''
"अन्तर्भूताः" = 'इई|उऊ अनदीसंज्ञकम् - सखि'
"प्रामुख्यम्" = '५'
"परिस्थितिः" = ''
"सूत्रम्" = 'शेषो घ्यसखि ।'
"उदाहरणम्" = 'हरिः।'
"विवरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अन्तर्भूताः" = ''
"प्रामुख्यम्" = ''
"परिस्थितिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"विवरणम्" = ''
