[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = 'धातोः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = 'उपपदम्'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = 'तत्रोपपदं सप्तमीस्थम्‌ ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कृत्'
"संज्ञा" = 'कृत्'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = 'अतिङ् धातुविहिताः'
"विवरणम्" = ''
"सूत्रम्" = '''
कृदतिङ् ।
(वा असरूपोऽस्त्रियाम्)'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'परिभाषा'
"संज्ञा" = ''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = '''
अस्मिन् धात्वधिकारे ऽसमानरूपः प्रत्ययो विकल्पेन बाधको भवति। 
स्त्र्यधिकारविहितप्रत्ययं वर्जयित्वा।'''
"सूत्रम्" = 'वाऽसरूपोऽस्त्रियाम् ।'
"उदाहरणम्" = 'ण्वुल्तृचौ ३।१।१३३ उत्सर्गौ, इगुपधज्ञाप्रीकिरः कः ३।१।१३५ इत्यपवादः, तद्विषये ण्वुल्तृचौ ३।१।१३३ अपि भवतः।'
"अभावोदाहरणम्" = ' असरूप इति किम्? कर्मण्यण् ३।२।१ इत्युत्सर्गः, आतो ऽनुपसर्गे कः ३।२।३ इत्यपवादः, सनित्यं बाधको भवति।'

[[data]]
"समूहः" = 'कृत्'
"संज्ञा" = 'कृत्य'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = '''
तव्य । तव्यत् । अनीयर् । यत् (य) । केलिमर् (एलिम) । ण्यत् (य) । क्यप् (य) । 
'''
"विवरणम्" = ''
"सूत्रम्" = '''
कृत्याः प्राङ् ण्वुलः ।
तव्यत्तव्यानीयरः ।
केलिमर उपसंख्यानम् (वा)'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कृत्'
"संज्ञा" = 'निष्ठा'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = 'क्त क्तवतु'
"विवरणम्" = ''
"सूत्रम्" = 'क्तक्तवतू निष्ठा ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कृत्'
"संज्ञा" = 'सत्'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = 'शतृँ शानच्'
"विवरणम्" = ''
"सूत्रम्" = 'तौ सत्'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = ''
"संज्ञा" = ''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कृत्'
"संज्ञा" = 'उणादिः'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कालः'
"संज्ञा" = 'अद्यतनः'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = '''
वर्तमान-आह्नस्य कालः।
इदानीन्तन इति न।'''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कालः'
"संज्ञा" = 'अनद्यतनः'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'कालः'
"संज्ञा" = 'परोक्षभूतः'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = '''
बहु-पूर्वकालिकं वा कुड्य-कुट-अन्तरितं वृत्तं।
कृतस्य स्मरणे कर्तुरत्यन्तापह्नवेऽपि च,
कर्मकर्त्रोरदृश्यत्वे त्रिषु विद्यात् परोक्षताम्।'''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = '''
शुद्धधातुः।
औपदेशिकधातुः।'''
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = 'भ्वादयो धातवः॥'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'आतिदेशिकः।'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = 'सनाद्यन्ताः॥'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'सकर्मकः'
"अपरसंज्ञा" = 'द्विकर्मकः'
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = 'दुह्-याच्-पच्-दण्ड्-रुधि-प्रच्छि-चि-ब्रू-शासु-जि-मथ्-मुष्-नी--हृ-कृष्-वह्।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'सकर्मकः'
"अपरसंज्ञा" = 'उपदेशे अकर्मकोऽपि'
"अन्तर्भूतानि" = ''
"विवरणम्" = 'देशः कालो भावो गन्तव्योऽध्वा - एतैर् योगे'
"सूत्रम्" = 'अकर्मकधातुभिर्योगे देशः कालो भावो गन्तव्योऽध्वा च कर्मसंज्ञक इति वाच्य"मिति वार्तिकेन अकर्मकधातूनामपि देशकालादिकर्मत्वम्।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'अकर्मकः'
"अपरसंज्ञा" = ''
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = '''

लज्‍जासत्‍तास्थितिजागरणं वृद्धिक्षयभयजीवनमरणम्
शयनक्रीडारुचिदीप्‍त्‍यर्थं धातुगणं तमकर्मकमाहु: ।।'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'अकर्मकः'
"अपरसंज्ञा" = '''
उपदेशे सकर्मकोऽपि
अर्थान्तरे| धातोर् अन्ते शब्दे|
|प्रसिद्धे कर्मणि'''
"अन्तर्भूतानि" = ''
"विवरणम्" = '''

अर्थान्तरे प्रयोगः।
कर्मणि प्रसिद्धे सति।
धातोः अन्ते शब्दः।'''
"सूत्रम्" = '''
धातोरर्थान्तरे वृत्तेर्धात्वर्थेनोपसंग्रहात्। 
प्रसिद्धेरविवक्षातः कर्मणो ऽकर्मिका क्रिया // वाप ३,७.८८ //'''
"उदाहरणम्" = '''
देवदत्तः पचति।
भारं वहति - नदी वहति।
मेघो वर्षति।
शब्दायते देवदत्तः।'''
"अभावोदाहरणम्" = ''

[[data]]
"समूहः" = 'धातुः'
"संज्ञा" = 'अकर्मकः'
"अपरसंज्ञा" = 'कर्मण: अविवक्षायामपि सकर्मकक्रिया - क्वचित्।'
"अन्तर्भूतानि" = ''
"विवरणम्" = ''
"सूत्रम्" = '''
धातोरर्थान्तरे वृत्तेर्धात्वर्थेनोपसंग्रहात्। 
प्रसिद्धेरविवक्षातः कर्मणो ऽकर्मिका क्रिया // वाप ३,७.८८ //'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
