[[data]]
"संज्ञा" = 'निपात'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'अधिरीश्वरे-(1.4.96). इति यावत् निपाताः'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'प्राग्रीश्वरान्निपाताः'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'च। वा। ह। अह। एव। एवम्। नूनम्। शश्वत्। युगपत्। सूपत्। कूपत्। कुवित्। नेत्। चेत्। चण्। कच्चित्। यत्र। नह। हन्त। माकिम्। नकिम्। माङ्। माङो ङकारो विशेषणार्थः, माङि लुङ् ३।३।१७५ इति। इह न भवति, मा भवतु, म भविष्यति। नञ्। यावत्। तावत्। त्वा। त्वै। द्वै। रै। श्रौषट्। वौषट्। स्वाहा। वषट्। स्वधा। ओम्। किल। तथा। अथ। सु। स्म। अस्मि। अ। इ। उ। ऋ। ल्̥। ए। ऐ। ओ। औ। अम्। तक्। उञ्। उकञ्। वेलायाम्। मात्रायाम्। यथा। यत्। यम्। तत्। किम्। पुरा। अद्धा। धिक्। हाहा। हे। है। प्याट्। पाट्। थाट्। अहो। उताहो। हो। तुम्। तथाहि। खलु। आम्। आहो। अथो। ननु। मन्ये। मिथ्या। असि। ब्रूहि। तु। नु। इति। इव। वत्। चन। बत। इह। शम्। कम्। अनुकम्। नहिकम्। हिकम्। सुकम्। सत्यम्। ऋतम्। श्रद्धा। इद्धा। मुधा। नो चेत्। न चेत्। नहि। जातु। कथम्। कुतः। कुत्र। अव। अनु। हाहौ। हैहा। ईहा। आहोस्वित्। छम्बट्। खम्। दिष्ट्या। पशु। वट्। सह। आनुषक्। अङ्ग। फट्। ताजक्। अये। अरे। चटु। बाट्। कुम्। खुम्। घुम्। हुम्। आईम्। शीम्। सीम्। वै।'
"विवरणम्" = 'असत्त्वे इति किम्? पशुर् वै पुरुषः।'
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'चादयोऽसत्त्वे'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'निपातः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
उपसर्गप्रतिरूपकाः अवदत्तम् विदत्तं च प्रदतं च अदिकर्मणि।
सुदत्तम् अनुदत्तं च निदत्तम्'''
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = '''
उपसर्गविभक्तिस्वरप्रतिरूपकाश्च निपाताः।
सुदत्तम् अनुदत्तं च निदत्तम् इति चेष्यते।  (वा)'''
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = 'निपातः'
"उपगणः" = '५'
"गृहितानि/ उदाहरणम्" = 'प्र, परा, अप, सम्, अनु, अव, निस्, निर्, दुस्, दुर्, वि, आङ्, नि, अधि, अपि, अति, सु, उत्, अभि, प्रति, परि, उप॥ '
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'प्रादयः'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उपसर्गः'
"गणः" = 'निपातः'
"उपगणः" = '५'
"गृहितानि/ उदाहरणम्" = 'प्रादयः +क्रिया'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'उपसर्गाः क्रियायोगे'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = '५'
"गृहितानि/ उदाहरणम्" = 'प्रादयः +क्रिया'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'गतिश्च'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = '५'
"गृहितानि/ उदाहरणम्" = '''
ऊर्यादयः शब्दाः च्व्यन्ता डजन्ताश्च (+ कृ|भू|अस्ति।)
'''
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'ऊर्यादिच्विडाचश्च'
"उदाहरणम्" = 'ऊरीउररीशब्दावङ्गीकरने विस्तारे च। ऊरीकृत्य। ऊरीकृतम्। यदुरीकरोति। उररीकृत्य। उररीकृतम्। यदुररीकरोति। पापी। ताली। आत्ताली। वेताली। धूसी। शकला। संशक्ला। ध्वंसकला। भ्रंशकला। एते शकलादयो हिंसायम्। शकलाकृत्य। संशकलाकृत्य। ध्वंसकलाकृत्य। भ्रंशकलाकृत्य। गुलुगुध पीडार्थे गुलुगुधाकृत्य। सुजूःसहार्थे सजूःकृत्य। फलू, फली, विक्ली, आक्ली इति विकारे फलू कृत्य। फली कृत्य। विक्ली कृत्य। आलोओष्टी। करली। केवाली। शेवाली। वर्षाली। मस्मसा। मसमसा। एते हिंसायाम्। वषट्। वौषट्। श्रौषट्। स्वाहा। स्वधा। वन्धा। प्रादुस्। श्रुत्। आविस्। च्व्यन्ताः खल्वपि शुक्लीकृत्य। शुक्लीकृतम्। यच्छुक्लीकरोति। डाच् पटपटाक्रृत्य। पटपटाकृतम्। यत्पटपटकरोति।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = '५'
"गृहितानि/ उदाहरणम्" = '''
अनुकरण-शब्दाः (+ क्रिया )
(अनुकरण-शब्दाः + इति + क्रिया इति न)'''
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अनुकरणं चानितिपरम्'
"उदाहरणम्" = 'खाट्कृत्य। खाट्कृतम्। यत्खाट्करोति। अनितिपरम् इति किम्? खाडिति कृत्वा निरष्ठीवत्।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'सत्, असत्'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'आदरानादरयोः सदसती'
"उदाहरणम्" = 'सत्कृत्य। सत्कृतम्। यत्सत्करोति। असत्कृत्य। असत्कृतम्। यदसत्करोति। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अलम् (भूषणे)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'भूषणेऽलम्'
"उदाहरणम्" = 'अलङ्कृत्य। अलङ्कृतम्।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अन्तर् (अपरिग्रहे)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अन्तरपरिग्रहे'
"उदाहरणम्" = 'अन्तर्हत्य। अन्तर्हतम्। यदन्तर्हन्ति।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'कणे, मनस् (श्रद्धाप्रतीघाते)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'कणेमनसी श्रद्धाप्रतीघाते'
"उदाहरणम्" = '''
कणेहत्य पयः पिबति। मनोहत्य पयः पिबति।
(=तावत् पिबति यावदस्य अभिलाशो निवृत्तः। श्रद्धा प्रतिहता इत्यर्थः।)'''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'पुरः'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'पुरोऽव्ययम्'
"उदाहरणम्" = 'पुरस्कृत्य। पुरस्कृतम्। यत् पुरस् करोति।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अस्तम्'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अस्तं च'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अच्छ'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अच्छ गत्यर्थवदेषु'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अदः'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अदोऽनुपदेशे'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'तिरः'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'तिरोऽन्तर्द्धौ'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'तिरः (+ कृ) विकल्पेन'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'विभाषा कृञि'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उपाजे, अन्वाजे  (+ कृ) विकल्पेन'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'उपाजेऽन्वाजे'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'साक्षात् प्रभृति (+ कृ) विकल्पेन'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'साक्षात्प्रभृतीनि च'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उरस् मनस् (अनत्याधाने, + कृ) विकल्पेन'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अनत्याधान उरसिमनसी'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'मध्ये पदे निवचने (+ कृ) विकल्पेन'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'मध्येपदेनिवचने च'
"उदाहरणम्" = 'मद्येकृत्य, मध्ये कृत्वा। पदेकृत्य, पदे कृत्वा।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'हस्ते पाणौ (+ कृ) '
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'नित्यं हस्ते पाणावुपयमने'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्राध्वम् (+ कृ) '
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'प्राध्वं बन्धने'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गतिः'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ' जीविका उपनिषत् (+कृ)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'जीविकोपनिषदावौपम्ये'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = '''
गति-उपसर्ग-संज्ञा-नियमः/
गति-उपसर्ग-प्रयोग-नियमः'''
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उपसर्गाः, गतिसंज्ञकाः '
"विवरणम्" = 'उपसर्गसंज्ञकाः तथा गतिसंज्ञकाः शब्दाः धातोः पूर्वम् एव भवन्ति । '
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'ते प्राग्धातोः'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = '''
गति-उपसर्ग-संज्ञा-नियमः/
गति-उपसर्ग-प्रयोग-नियमः'''
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उपसर्गाः, गतिसंज्ञकाः '
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'छन्दसि परेऽपि'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = '''
गति-उपसर्ग-संज्ञा-नियमः/
गति-उपसर्ग-प्रयोग-नियमः'''
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उपसर्गाः, गतिसंज्ञकाः '
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'व्यवहिताश्च'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अनु उप प्रति परि अभि अधि सु अति अपि अप आङ् इत्येतेषां कर्मप्रवचनीयसंज्ञा।'
"विवरणम्" = '''
कर्म क्रियां प्रोक्तवान् इति कर्मप्रवचनीयः। क्रियाम् बोधयति, किञ्च न साक्षात्।
संज्ञाप्रयोजनम् - क्वचिद् उपसर्गसंज्ञावारणम् (तेन षत्ववारणम्, स्वरभेदः)।
कुगतिप्रादय इत्यनेन समासस्य वारणम्।'''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'कर्मप्रवचनीयाः'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अनु (लक्षणे द्योत्ये)'
"विवरणम्" = '??'
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अनुर्लक्षणे'
"उदाहरणम्" = ' शाकल्यस्य संहितामनु प्रावर्षत्। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अनु (सहार्थे)'
"विवरणम्" = 'सहार्थोऽत्र तृतीयार्थः। '
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'तृतीयाऽर्थे'
"उदाहरणम्" = 'नदीम् अन्ववसिता सेना।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अनु (हीनार्थे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'हीने'
"उदाहरणम्" = 'अनु शाकटायनं वैयाकरणाः। अन्वर्जुनं योद्धारः।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'उप (अधिके हीने च द्योत्ये)'
"विवरणम्" = ''
"प्रामुख्यम्" = '३'
"सूत्रम्" = 'उपोऽधिके च'
"उदाहरणम्" = '''
उप शाकटायनं वैयाकरणाः।
'''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अप | परि (वर्जने)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपपरी वर्जने'
"उदाहरणम्" = '''
अप त्रिगर्तेभ्यो वृष्टो देवः।
परि त्रिगर्तेभ्यो वृष्टो देवः।'''
"अनुदाहरणम्" = 'वर्जने इति किम्? ओदनं परिषिञ्चति।'

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'आङ् मर्यादायाम्'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'आङ् मर्यादावचने'
"उदाहरणम्" = ' आ पाटलिपुत्राद् वृष्टो देवः। आ कुमारं यशः पाणिनेः।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्रति |परि |अनु (लक्षणे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'लक्षणेत्थम्भूताख्यानभागवीप्सासु प्रतिपर्यनवः'
"उदाहरणम्" = '''
वृक्षं प्रति विद्योतते विद्युत्। वृक्षं परि। वृक्षम् अनु।
'''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्रति |परि |अनु (इत्थम्भूते)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'लक्षणेत्थम्भूताख्यानभागवीप्सासु प्रतिपर्यनवः'
"उदाहरणम्" = 'साधुर् देवदत्तो मातरम् प्रति। मातरम् परि। मातरम् अनु।'
"अनुदाहरणम्" = 'ओदनं परिषिञ्चति।'

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्रति |परि |अनु (भागे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'लक्षणेत्थम्भूताख्यानभागवीप्सासु प्रतिपर्यनवः'
"उदाहरणम्" = 'यदत्र मां प्रति स्यात्। माम् परि स्यात्। मामनु स्यात्।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्रति |परि |अनु (वीप्सायाम्)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'लक्षणेत्थम्भूताख्यानभागवीप्सासु प्रतिपर्यनवः'
"उदाहरणम्" = 'वृक्षं वृक्षम् प्रति सिञ्चति। परि सिञ्चति। अनु सिञ्चति। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अभि (अभागे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अभिरभागे'
"उदाहरणम्" = ' वृक्षम् अभि विद्योतते विद्युत्। '
"अनुदाहरणम्" = 'यदत्र मम अभि (भागः) तद् दीयताम्।'

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'प्रतिः प्रतिनिधिप्रतिदानयोः'
"विवरणम्" = ''
"प्रामुख्यम्" = '४'
"सूत्रम्" = 'प्रतिः प्रतिनिधिप्रतिदानयोः'
"उदाहरणम्" = '''
अभिमन्युरर्जुनतः प्रति।
माषानस्मै तिलेभ्यः प्रति यच्छति। '''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अधि परि (अनर्थकौ??)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'अधिपरी अनर्थकौ'
"उदाहरणम्" = 'कुतो ऽध्यागच्छति। कुतः पर्यागच्छति। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'सु (पूजायाम्)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'सुः पूजायाम्'
"उदाहरणम्" = 'सु सिक्तं भवता। सु स्तुतं भवता। (उपसर्गसंज्ञाऽश्रयं षत्वं न भवति।)'
"अनुदाहरणम्" = 'पूजायाम् इति किम्? सुषिक्तं किं तवात्र?'

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अति (अतिक्रमणे, पूजायाम्)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अतिरतिक्रमणे च'
"उदाहरणम्" = '''
अति सिक्तम् एव भवता। अति स्तुतम् एव भवता।
'''
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अपि (पदार्थे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपिः पदार्थसम्भावनान्ववसर्गगर्हासमुच्चयेषु'
"उदाहरणम्" = 'सर्पिषो ऽपि स्यात्। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अपि (सम्भावने)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपिः पदार्थसम्भावनान्ववसर्गगर्हासमुच्चयेषु'
"उदाहरणम्" = 'अपि सिञ्चेन् मूलकसहस्रम्? अपि स्तुयाद् राजानम्?'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अपि (अन्ववसर्गे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपिः पदार्थसम्भावनान्ववसर्गगर्हासमुच्चयेषु'
"उदाहरणम्" = 'अपि सिञ्च। अपि स्तुहि।'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अपि (गर्हायाम्)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपिः पदार्थसम्भावनान्ववसर्गगर्हासमुच्चयेषु'
"उदाहरणम्" = 'धिग् जाल्मं देवदत्तम्, अपि सिञ्चेत् पलाण्डुम्। अपि स्तुयाद् वृषलम्। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अपि (समुच्चये)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अपिः पदार्थसम्भावनान्ववसर्गगर्हासमुच्चयेषु'
"उदाहरणम्" = 'अपि सिञ्च। अपि स्तुहि। (= सिञ्च च स्तुहि च। उपसर्गसंज्ञाबाधनात् षत्वम् न भवति।)'
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अधि (ईश्वरे)'
"विवरणम्" = ''
"प्रामुख्यम्" = '५'
"सूत्रम्" = 'अधिरीश्वरे'
"उदाहरणम्" = 'अधि ब्रह्मदत्ते पञ्चालाः। अधि पञ्चालेषु ब्रह्मदत्तः। '
"अनुदाहरणम्" = ''

[[data]]
"संज्ञा" = 'कर्मप्रवचनीया'
"गणः" = 'निपातः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अधि (कृ, विकल्पेन)'
"विवरणम्" = ''
"प्रामुख्यम्" = ''
"सूत्रम्" = 'विभाषा कृञि'
"उदाहरणम्" = ''
"अनुदाहरणम्" = ''
