[[data]]
"संज्ञा" = 'अण्'
"गणः" = ''
"उपगणः" = 1
"गृहितानि/ उदाहरणम्" = 'अ इ उ ण्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'ऋक्'
"गणः" = ''
"उपगणः" = 2
"गृहितानि/ उदाहरणम्" = 'ऋ ऌ क्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'एङ्'
"गणः" = ''
"उपगणः" = 3
"गृहितानि/ उदाहरणम्" = 'ए ओ ङ्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'ऐच्'
"गणः" = ''
"उपगणः" = 4
"गृहितानि/ उदाहरणम्" = 'ऐ औ च्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'हट्'
"गणः" = ''
"उपगणः" = 5
"गृहितानि/ उदाहरणम्" = 'ह य व र ट्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'लण्'
"गणः" = ''
"उपगणः" = 6
"गृहितानि/ उदाहरणम्" = 'ल ण्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'ञम्'
"गणः" = ''
"उपगणः" = 7
"गृहितानि/ उदाहरणम्" = 'ञ म ङ ण न म्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'nasalize the sound of the previous letter in the varga।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'झञ्'
"गणः" = ''
"उपगणः" = 8
"गृहितानि/ उदाहरणम्" = 'झ भ ञ्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = 9
"गृहितानि/ उदाहरणम्" = 'घ ढ ध ष्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'जश्'
"गणः" = ''
"उपगणः" = 10
"गृहितानि/ उदाहरणम्" = 'ज ब ग ड द श्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'अल्पप्राणीयानि मृदुवर्गीयव्यञ्जनानि'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = 11
"गृहितानि/ उदाहरणम्" = 'ख फ छ ठ थ च ट त व्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = 12
"गृहितानि/ उदाहरणम्" = 'क प य्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = 13
"गृहितानि/ उदाहरणम्" = 'श ष स र्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = 14
"गृहितानि/ उदाहरणम्" = 'ह ल्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'ळ् ळ्ह'
"प्रामुख्यम्" = ''
"विवरणम्" = 'ड्-ढ्-योः स्थाने क्वचित् वेदे।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'अश्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'स्वराः हट् मृदुव्यञ्जनानि'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'झल्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
ऊष्माण-अनुनासिक-
वर्जित-व्यञ्जनम्'''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'झय्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
अनुनासिक-
वर्जित-वर्गीय-व्यञ्जनम्'''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'खर्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'कर्कशव्यञ्जनानि'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'हश्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'मृदुव्यञ्जनानि'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = '?त्'
"गणः" = ''
"उपगणः" = 'इत्'
"गृहितानि/ उदाहरणम्" = 'अत् = अ। आत् = आ।'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'तपरस्तत्कालस्य'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गुरुः'
"गणः" = 'अक्षरम्'
"उपगणः" = 'छन्दःशास्त्रे'
"गृहितानि/ उदाहरणम्" = '''

दीर्घम् गुरु।
संयुक्ताक्षरपरं गुरु।
विसर्गानुस्वारपरं गुरु।
पादस्तस्यान्ते वर्तमानो लघुरपि विभाषया गुरुः - विशिष्य पद्यार्धे। '''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '''
सानुस्वारश्च दीर्घश्च विसर्गी च गुरुर्भवेत् । वर्णः संयोगपूर्वश्च तथा पादान्तगोऽपि वा ॥
सानुस्वारो विसर्गान्तो दीर्घो युक्तपरश्च यः। वा पादान्ते त्वसौ वक्रो। ज्ञेयोऽन्यो मात्रिको ऋजुः॥
"पादस्तस्यान्ते वर्तमानो लघुरपि विभाषया गुरुः स्यात्‌ । स च कविसमयव्यवहारात्‌ द्वितीयचतुर्थयोरेव पादयोरन्ते वेदितव्यः ।" इति सुल्हणः।'''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गुरुः'
"गणः" = 'अक्षरम्'
"उपगणः" = 'व्याकरणे'
"गृहितानि/ उदाहरणम्" = '''
दीर्घम् गुरु।
संयुक्ताक्षरपरं गुरु।'''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'लघुः'
"गणः" = 'अक्षरम्'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
ह्रस्वं लघु।
'''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'गुरुलक्षणे यथा।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'शिथिलद्वित्त्वपरः'
"गणः" = ''
"उपगणः" = 'अक्षरम्'
"गृहितानि/ उदाहरणम्" = '''
संयुक्ताक्षरपरेषु पदान्तेषु विकल्पेन।
ह्रस्वानुस्वारः विकल्पेन लघु???
प्र-ह्रे परे विकल्पेन लघु।'''
"प्रामुख्यम्" = ''
"विवरणम्" = '''
अपरूपम् प्रयोक्तव्यम् इति ।
'''
"सूत्रम्" = '''
प्रह्रे वा॥ इति पिङ्गलः। प्रह्रे उपलक्षणम् इति केचित्।
पदादाविह वर्णस्य संयोगः क्रमसंज्ञकः। पुरःस्थितेन तेन स्याल् लघुतापि क्वचिद्गुरोः॥
सुल्हणपाठे "पदादाविह" इत्यादि।
दीर्घं संयोगपरं तथा प्लुतव्यञ्जनान्तम् ऊष्मान्तम्।
सानुस्वारञ्च गुरु क्वचिद् अवसानेऽपि लघ्वन्त्यम्॥ ??
वर्णो गुरुर्मतो ह्रेप्रे पादान्ते चापि वा लघुः (छन्दःकौस्तुभे)
यदा तीव्रप्रयत्नेन संयोगादेरगौरवम्
न च्छन्दोभङ्गमप्याहुस्तदा दोषाय सूरयः (छन्दःप्रकाशे)
यदि हि युक्तपरः श्रममन्तरा लघुरपि प्रभवेच्चरणान्तरा (?)
अणु वदन्ति न वृत्तविदूषणं तमथ भूषणमेव मनीषिणः (वृत्तप्रत्ययकौमुद्याम्)'''
"उदाहरणम्" = ' कालिदास-माघप्रयोगौ वृत्तरत्नाकरटीकायां दर्शितम्।'


[[data]]
"संज्ञा" = 'ह्रस्व'
"गणः" = ''
"उपगणः" = 'मात्रा'
"गृहितानि/ उदाहरणम्" = 'अचाम् एओऐऔ विहाय'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'दीर्घ'
"गणः" = ''
"उपगणः" = 'मात्रा'
"गृहितानि/ उदाहरणम्" = 'ऌ विहाय अन्ये अचाम्'
"प्रामुख्यम्" = ''
"विवरणम्" = 'कॢपि (कल्पते) इत्यस्मिन्नेव दृश्यते।'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्लुत'
"गणः" = ''
"उपगणः" = 'मात्रा'
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = 'ॡ न क्वचित्!'
"सूत्रम्" = ''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'वृद्धिः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'आ ऐ औ आर्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'वृद्धिः आदैच्'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'गुणः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अ ए ओ अर्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'अदेङ् गुणः'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'संयोगः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'हल्+हल्'
"प्रामुख्यम्" = '५'
"विवरणम्" = ''
"सूत्रम्" = 'हलोऽनन्तराः संयोगः ।'
"उदाहरणम्" = 'क्स्'

[[data]]
"संज्ञा" = 'अनुनासिकः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = '५'
"विवरणम्" = ''
"सूत्रम्" = 'मुखनासिकावचनोऽनुनासिकः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सवर्णम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
(स्वरः, तुल्य-स्थान-अभ्यन्तरप्रयत्नः स्वरः)
(हल्, तुल्य-स्थान-अभ्यन्तरप्रयत्नः हल्)'''
"प्रामुख्यम्" = '५'
"विवरणम्" = '''
समानस् स्थानः। समानम् आभ्यन्तरप्रयत्नम्। सावर्ण्यविषये बाह्यप्रयत्नानां न कोऽपि विचारः।
'''
"सूत्रम्" = '''
तुल्यास्यप्रयत्नम् सवर्णम्।
नाज्झलौ।
ऋऌकारयोः सावर्ण्यम् वाच्यम्।'''
"उदाहरणम्" = '''
अ+अ
इ+ई
क् ख्'''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'इत्-उत्-एत्-अन्तं द्विवचनम्।'
"प्रामुख्यम्" = '४'
"विवरणम्" = ''
"सूत्रम्" = 'ईदूदेद्द्विवचनं प्रगृह्यम् ।'
"उदाहरणम्" = 'हरी। अस्मू। अमी। पचेते।'

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अदस् रूपेषु अमू अमी।'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'अदसो मात् ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'शे ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'निपातः एकाच् अनाङ्'
"प्रामुख्यम्" = '४'
"विवरणम्" = ''
"सूत्रम्" = 'निपात एकाजनाङ् ।'
"उदाहरणम्" = '''
इ इन्द्रः। इ विस्मयार्थे। उ उमेशः।  उ सन्देहे।
परन्तु चादिगणे स्थितः आ - आ अहं स्मरामि। आ स्मरणे। न तु आङ् उपसर्गः (आ +उष्णम् = ओष्णम्।)।
न च हल्-सहित एकाच् - "चादयोऽसत्त्वे" इत्यादिनां सूत्राणां ज्ञापनेन। ("एकाचो द्वे प्रथमस्य" इत्यत्र तु हल्सहित एकाच् ग्राह्यः - "न न्द्रा संयोगादयः" सूत्रं निरवकाशं मा भूत् । )'''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'ओत्-अन्त-निपातः।'
"प्रामुख्यम्" = '४'
"विवरणम्" = ''
"सूत्रम्" = 'ओत् ।'
"उदाहरणम्" = 'अहो!'

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'दूरात् संबोधने जातः प्लुतः।'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'सम्बुद्धौ शाकल्यस्येतावनार्षे ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'उञः ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'ऊँ ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रगृह्यम्‌'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'ईदूतौ च सप्तम्यर्थे ।'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = ''
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'सम्प्रसारणम्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'इ उ ऋ ऌ [यणः स्थाने आगताः]'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'इग्यणः सम्प्रसारणम्'
"उदाहरणम्" = 'वप् -उप्तम् यज् - इष्टम्'

[[data]]
"संज्ञा" = 'अवसानम्'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'स्वरहीनव्यञ्जनानि।'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'विरामोऽवसानम्॥'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'वृद्धः'
"गणः" = ''
"उपगणः" = 'पदे'
"गृहितानि/ उदाहरणम्" = '''
भारत औषद ऐश्वर्य
त्वत् भवत्
हरिनारायण विश्वास'''
"प्रामुख्यम्" = ''
"विवरणम्" = '''
स्वरेषु प्रथमः वृद्धिः।
त्यत्-आदि - त्वत् भवत्।
नामधेयाः। '''
"सूत्रम्" = '''
वृद्धिर्यस्याचामादिस्तद्()वृद्धम्॥
त्यदादीनि च॥
'''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उपधा'
"गणः" = ''
"उपगणः" = 'पदे'
"गृहितानि/ उदाहरणम्" = 'शब्दे अन्तिमपूर्ववर्णः'
"प्रामुख्यम्" = '५'
"विवरणम्" = ''
"सूत्रम्" = 'अलोऽन्त्यात्पूर्व उपधा॥'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'टि'
"गणः" = ''
"उपगणः" = 'पदे'
"गृहितानि/ उदाहरणम्" = ''
"प्रामुख्यम्" = ''
"विवरणम्" = 'हविस् – टि-भागः is इस्।'
"सूत्रम्" = 'अचोऽन्त्यादि टि'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'प्रत्याहारः'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = 'अच् इण् हल्'
"प्रामुख्यम्" = ''
"विवरणम्" = ''
"सूत्रम्" = 'आदिर् अन्त्येन सहेता॥'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'उत्तमम् |‌उपोत्तमम्।'
"गणः" = ''
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = '''
३+अक्षरपदेषु अन्तिमाक्षरम् उत्तमम्।
उपोत्तमम् तत्पूर्वम्।'''
"सूत्रम्" = 'उत्तमशब्दः स्वभावात् त्रिप्रभृतीनामन्त्यमक्षरमाह। इति काशिका'
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'इत्'
"गणः" = 'वर्णः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
अच् अनुनासिकम्। इर्।
(उपदेशे) हलः।  विभक्तौ न तुँ स् म्।
आदिः ञि टु डु च।
प्रत्ययादौ -
ल श कुँ अतद्धिते।
ष् चुँ टुँ च।'''
"विवरणम्" = 'footnote सदृशं। कार्यं कृत्वा लुप्ताः'
"सूत्रम्" = '''
उपदेशेऽजनुनासिक इत्।
हलन्त्यम्। न विभक्तौ तुस्माः। 'इर्' इत्संज्ञा वाच्या।
आदिर् ञिटुडवः॥
षः प्रत्ययस्य ॥
चुँ-टूँ। 1.3.7
लशक्वतद्धिते।
तस्य लोपः (१.३.९)॥ अदर्शणम् लोपः॥
'''
"उदाहरणम्" = ''

[[data]]
"संज्ञा" = 'आदिः'
"गणः" = 'वर्णः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = ''
"विवरणम्" = 'इत्-संज्ञाम् त्यक्त्वा प्राप्तः वर्णः।'
"सूत्रम्" = ''
"उदाहरणम्" = 'शप् अदादिः। श्ना नकारादिः।'

[[data]]
"संज्ञा" = 'यतिः'
"गणः" = 'वर्णः'
"उपगणः" = ''
"गृहितानि/ उदाहरणम्" = '''
पद्यवचने विरामः।
समस्तपदे उपपदान्ते भवेत् - यथा "सीताराम" इत्यस्मिन् सीता-अन्ते।'''
"विवरणम्" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
