[[data]]
"अङ्गम्" = '*'
"प्रत्ययः/ विवक्षा" = 'प्राक्क्रीतार्थाः'
"परिणामः" = 'छ'
"प्रासिद्ध्यम्" = '५'
"समूहः" = ''
"सूत्रम्" = 'प्राक् क्रीताच्छः ।'
"प्रभावोदाहरणम्" = 'वत्सेभ्यो हितः वत्सीयो गोधुक्। करभीयः उष्ट्रः। अकरभीयः। अवत्सीयः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'उवर्णान्तात् प्रातिपदिकात् गवाऽदिभ्यश्च'
"प्रत्ययः/ विवक्षा" = 'प्राक्क्रीतार्थाः'
"परिणामः" = 'यत्'
"प्रासिद्ध्यम्" = '४'
"समूहः" = ''
"सूत्रम्" = '''
उगवादिभ्योऽत्‌ ।
["ओर्गुणः" ६।४।१४६ "वान्तो यि प्रत्यये" ६।१।७६ इत्यवादेशः।]'''
"प्रभावोदाहरणम्" = 'शङ्कव्यं दारु। पिचव्यः कार्पासः। कमण्डलव्या मृत्तिका। गवादिभ्यः खल्वपि गव्यम्। हविष्यम्। सनङ्गुर्नाम चर्मविकारः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'कम्बलात्'
"प्रत्ययः/ विवक्षा" = 'प्राक्क्रीतार्थाः'
"परिणामः" = 'यत्'
"प्रासिद्ध्यम्" = '१'
"समूहः" = ''
"सूत्रम्" = 'कम्बलाच्च संज्ञायाम् ।'
"प्रभावोदाहरणम्" = 'कम्बल्यम् ऊर्णापलशतम्।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अपूपादिः'
"प्रत्ययः/ विवक्षा" = 'प्राक्क्रीतार्थाः'
"परिणामः" = 'यत् वा'
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'विभाषा हविरपूपादिभ्यः ।'
"प्रभावोदाहरणम्" = 'पूपादिभ्यः अपूप्यम्, अपूपीयम्। तण्डुल्यम्, तण्डुलीयम्। अपूप। तण्डुल। अभ्यूष। अभ्योष। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'अर्थः'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'तस्मै हितम् ।'
"प्रभावोदाहरणम्" = 'वत्सेभ्यो हितः वत्सीयो गोधुक्। करभीयः उष्ट्रः। अकरभीयः। अवत्सीयः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'शरीरावयवाद्यत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'खलयवमाषतिलवृषब्रह्मणश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'अजाविभ्यां थ्यन् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'आत्मन्विश्वजनभोगोत्तरपदात्‌ खः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'सर्वपुरुषाभ्यां णढञौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्मै हितम्'
"सूत्रम्" = 'माणवचरकाभ्यां खञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदर्थं विकृतेः प्रकृतौ '
"सूत्रम्" = 'तदर्थं विकृतेः प्रकृतौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदर्थं विकृतेः प्रकृतौ '
"सूत्रम्" = 'छदिरुपधिबलेः ढञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदर्थं विकृतेः प्रकृतौ '
"सूत्रम्" = 'ऋषभोपानहोर्ञ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदर्थं विकृतेः प्रकृतौ '
"सूत्रम्" = 'चर्म्मणोऽञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदस्य तदस्मिन् स्यादिति '
"सूत्रम्" = 'तदस्य तदस्मिन् स्यादिति ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तदस्य तदस्मिन् स्यादिति '
"सूत्रम्" = 'परिखाया ढञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''
