[[data]]
"अङ्गम्" = '''
-बहुव्रीहिनिर्वाह्यम्
- अन्येऽपवादाः
'''
"प्रत्ययः/ विवक्षा" = '''
"(तदस्य |
अस्मिन् ) अस्ति + निन्दास्तुत्यादि-विशेषः"'''
"परिणामः" = 'मतुबादयः'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'तदस्यास्त्यस्मिन्निति मतुप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = '''
"इति"शब्दः सूत्रे निन्दास्तुत्यादि-विशेषविवक्षासूचकः। 
'''

[[data]]
"अङ्गम्" = 'बहुव्रीहिनिर्वाह्यम्'
"प्रत्ययः/ विवक्षा" = '''
(तदस्य |
अस्मिन् ) अस्ति
- (
भूम| निन्दा |‌ प्रशंसा |‌नित्ययोगः| अतिशायने | संसर्गे| अस्तिविवक्षा)'''
"परिणामः" = '- मतुबादयः'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = '''
"बहुव्रीहिनिर्वाह्ये न भवन्ति मतुबादयः" इति सामान्यस्थितिः।
भूमनिन्दाप्रशंसासु नित्ययोगेऽतिशायने।
संसर्गेऽस्तिविवक्षायां भवन्ति मतुबादयः॥
– भा.पा.सू. ५२९४​​'''
"प्रभावोदाहरणम्" = '''

भूम्नि तावत् गोमान्। निन्दायाम् कुष्ठी। ककुदावर्तिनी। प्रशंसायाम् रूपवती कन्या। नित्ययोगे क्षीरिणो वृक्षाः। अतिशायने उदरिणी कन्या। संसर्गे दण्डी। छत्री। अस्तिविवक्षायाम् अस्तिमान्।'''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'गुणवचनम्'
"प्रत्ययः/ विवक्षा" = '''
(तदस्य |
अस्मिन् ) अस्ति'''
"परिणामः" = 'मतुप् → लुक्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'गुणवचनेभ्यो मतुपो लुग्वक्तव्यः।'
"प्रभावोदाहरणम्" = 'शुक्लो गुणो ऽस्य अस्ति शुक्लः पटः। कृष्णः। श्वेतः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
गुणात् ( रस। रूप। गन्ध। स्पर्श। शब्द। स्नेह। )
एकाचः। '''
"प्रत्ययः/ विवक्षा" = '''
(तदस्य |
अस्मिन् ) अस्ति'''
"परिणामः" = 'मतुप्, प्रायो न अन्ये'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'रसादिभ्यश्च ।'
"प्रभावोदाहरणम्" = 'सवान्। रूपवान्।'
"अभावोदाहरणम्\n" = '''
कथं रूपिणी कन्या, रूपिको दारकः? प्रायिकम् एतद् वचनम्।
रसनेन्द्रियादिग्राह्या गुणाः, तेषाम् अत्र पाठः। इह मा भूत्, रूपिणी, रूपिकः इति। शोभायोगो गम्यते। 
रसिको नटः इत्यत्र भावयोगः।'''
"विवरणम्" = 'रसादिभ्यः पुनर् वचनम् अन्यनिवृत्त्यर्थम्, अन्ये मत्वर्थीया मा भूवन्निति।'

[[data]]
"अङ्गम्" = 'प्राण्यङ्गः *+आत्'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'मतुप् लच्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = '''
प्राणिस्थादातो लजन्यतरस्याम् ।
प्राण्यङ्गादिति वक्तव्यम्। (वा)'''
"प्रभावोदाहरणम्" = 'चूडालः, चूडावान्। कर्णिकालः, कर्णिकावान्।'
"अभावोदाहरणम्\n" = 'प्राणिस्थातिति किम्? शिखावान् प्रदीपः। आतिति किम्? हस्तवान्। पादवान्।'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'सिध्म। गडु। मणि। नाभि। जीव। निष्पाव। पांसु। सक्तु। हनु। मांस। परशु। पार्ष्णिधमन्योर् दीर्घश्च। पार्ष्णीलः। धमनीलः। पर्ण। उदक। प्रज्ञा। मण्ड। पार्श्व। गण्ड। ग्रन्थि। वातदन्तबलललाटानामूङ् च। वातूलः। दन्तूलः। बलूलः। ललाटूलः। जटाघटाकलाः क्षेपे। जटालः। घटालः। कलालः। सक्थि। कर्ण। स्नेह। शीत। श्याम। पिङ्ग। पित्त। शुष्क। पृथु। मृदु। मञ्जु। पत्र। चटु। कपि। कण्डु। संज्ञा। क्षुद्रजन्तूपतापाच् च इष्यते। क्षुद्रजन्तु यूकालः। मक्षिकालः। उपताप विचर्चिकालः। विपादिकालः। मूर्च्छालः। सिध्मादिः।'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'मतुप् लच्'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'सिध्मादिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वत्सांसाभ्यां कामबले ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'इलच्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'फेनादिलच् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ' लोमन्। रोमन्। वल्गु। बभ्रौ। हरि। कपि। शुनि। तरु। लोमादिः।'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'श, मतुप्'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'लोमादिपामादिपिच्छादिभ्यः शनेलचः ।'
"प्रभावोदाहरणम्" = 'लोमशः, लोमवान्। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'पामन्। वामन्। हेमन्। श्लेष्मन्। कद्रु। बलि। श्रेष्ठ। पलल। सामन्। अङ्गात् कल्याणे। शाकीपललीदद्र्वां ह्रस्वत्वम् च। विष्वगित्युत्तरपदलोपश्चाकृतसन्धेः। लक्ष्म्या अच्च। पामादिः। '
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'न, मतुप्'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'लोमादिपामादिपिच्छादिभ्यः शनेलचः ।'
"प्रभावोदाहरणम्" = 'पामनः, पामवान्। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'पिच्छ। उरस्। घ्रुवका। क्षुवका। जटाघटाकलाः क्षेपे। वर्ण। उदक। पङ्क। प्रज्ञा। पिच्छादिः।'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'इलच्, मतुप्'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'लोमादिपामादिपिच्छादिभ्यः शनेलचः ।'
"प्रभावोदाहरणम्" = 'पिच्छिलः, पिच्छवान्।  कुमारीलः'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्रज्ञाश्रद्धाऽर्चावृत्तिभ्यो णः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तपःसहस्राभ्यां विनीनी ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अण् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सिकताशर्कराभ्यां च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'देशे लुबिलचौ च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दन्त उन्नत उरच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'ऊषसुषिमुष्कमधो रः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'द्युद्रुभ्यां मः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'केशाद्वोऽन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'गाण्ड्यजगात्‌ संज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'काण्डाण्डादीरन्नीरचौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'रजःकृष्यासुतिपरिषदो वलच् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दन्तशिखात्‌ संज्ञायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'ज्योत्स्नातमिस्राशृङ्गिणोजस्विन्नूर्जस्वलगोमिन्मलिनमलीमसाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
अत्
- (एकाक्षरः |‌कृत्|जातिः)'''
"प्रत्ययः/ विवक्षा" = 'तदस्यास्ति'
"परिणामः" = 'इनि ठन् मतुप्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = '''
अत इनिठनौ । (अन्यतरस्याम्)
एकाक्षरात् कृतो जातेः 
सप्तम्यां च न तौ स्मृतौ। '''
"प्रभावोदाहरणम्" = ' दण्डी, दण्डिकः। दण्डवान्। छत्रवान्।'
"अभावोदाहरणम्\n" = 'तपरकरणं किम्? श्रद्धावान्।'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'एकाक्षरः |कृत्| जातिः'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'मतुप्। न इनिठनौ प्रायः।'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = '''
एकाक्षरात् कृतो जातेः 
सप्तम्यां च न तौ स्मृतौ। '''
"प्रभावोदाहरणम्" = '''
एकाक्षरात् तावत् स्ववान्। खवान्। कृतः कारकवान्। 
जातेः व्याघ्रवान्। सिंहवान्।
सप्तम्याम् दन्डा अस्यां सन्ति दण्डवती शाला इति।'''
"अभावोदाहरणम्\n" = 'सर्वत्र सम्बध्यते इत्युक्तम्, तेन क्वचिद् भवत्यपि, कार्यी, हार्यी, तण्डुली, तण्दुलिकः इति।'
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'व्रीह्यादिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'तुन्द। उदर। पिचण्ड। घट। यव। व्रीहि। स्वाङ्गाद् विवृद्धौ च। तुन्दादिः।'
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = 'इलच् इनि ठन् मतुप्'
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तुन्दादिभ्य इलच् च ।'
"प्रभावोदाहरणम्" = 'उदरिलः, उदरी, उदरिकः, उदरवान्। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '(एक|गो) + *+अत्'
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'ठञ्, न मतुप्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'एकगोपूर्वाट्ठञ् नित्यम् ।'
"प्रभावोदाहरणम्" = '''
एकञ्च तच्छतं चैकशतम्। एकशतम् अस्य अस्ति इति ऐकशतिकः। 
गोपूर्वात् च गौशतिकः।'''
"अभावोदाहरणम्\n" = '''
अत इत्येव एकविंशतिरस्य अस्ति इति न भवति।
 षष्ठीतत्पुरुषे--एकशतवान्। ???'''
"विवरणम्" = 'नित्यग्रहणं मतुपो बाधनार्थम्।'

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'शतसहस्रान्ताच्च निष्कात्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'रूपादाहतप्रशंसयोरप्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अस्मायामेधास्रजो विनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'बहुलं छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'ऊर्णाया युस् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वाचो ग्मिनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'आलजाटचौ बहुभाषिणि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'स्वामिन्नैश्वर्ये ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
अर्शादिः आकृतिगणः।
[अर्शस्। उरस्। तुन्द। चतुर। पलित। जटा। घता। अभ्र। कर्दम। आम। लवण। स्वाङ्गाद्धीनात्। वर्णात्।]'''
"प्रत्ययः/ विवक्षा" = 'मत्वर्थे'
"परिणामः" = 'अच्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = 'अर्शआदिभ्योऽच् ।'
"प्रभावोदाहरणम्" = '''
अर्शसः। उरसः।
पीतोदकाः गावः = पीताः गावः। (पीतम् अस्याः अस्तीति पीता)
भुक्ताः ब्राह्मणाः। विभक्ताः ब्राह्मणाः।
गोपूर्वात् च गौशतिकः।'''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'द्वंद्वोपतापगर्ह्यात्‌ प्राणिस्थादिनिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वातातिसाराभ्यां कुक् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वयसि पूरणात्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सुखादिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'धर्मशीलवर्णान्ताच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'हस्ताज्जातौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वर्णाद्ब्रह्मचारिणि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'पुष्करादिभ्यो देशे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'बलादिभ्यो मतुबन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'संज्ञायां मन्माभ्याम्.ह् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'कंशंभ्यां बभयुस्तितुतयसः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तुन्दिवलिवटेर्भः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अहंशुभमोर्युस् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''
