[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = '[प्राग्दीव्यतोऽण् ।]'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'अण्'
"प्रासिद्ध्यम्" = '५'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'तस्येदम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'संवह् + तृच् अनिट्'
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'अण्'
"प्रासिद्ध्यम्" = '१'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'संवहेस्तुरणिट् च। (वा)'
"प्रभावोदाहरणम्" = 'संवोढुः स्वं सांवहित्रम्। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'रण्'
"प्रासिद्ध्यम्" = '१'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'आग्नीधः शरणे रण् भं च।(वा)'
"प्रभावोदाहरणम्" = 'आग्नीध्रम्।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'फेण्यण्'
"प्रासिद्ध्यम्" = '१'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = ' समिधामाधाने षेण्यण्।(वा)'
"प्रभावोदाहरणम्" = 'सामिधेन्यो मन्त्रः। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'रथ'
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'यत्'
"प्रासिद्ध्यम्" = '२'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'रथाद्यत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'अञ्'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'पत्त्रपूर्वादञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'अञ्'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'पत्त्राध्वर्युपरिषदश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'हल सीर'
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'ठक्'
"प्रासिद्ध्यम्" = '२'
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'हलसीराट्ठक् ।'
"प्रभावोदाहरणम्" = 'हलस्य इदं हालिकम्। सैरिकम्। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'वुन्'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'द्वंद्वाद्वुन् वैरमैथुनिकयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'वुञ्'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'गोत्रचरणाद्वुञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'ष्'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'संघाङ्कलक्षणेष्वञ्यञिञामण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'शाकलाद्वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'छन्दोगौक्थिकयाज्ञिकबह्वृचनटाञ्ञ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'न दण्डमाणवान्तेवासिषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = 'छ'
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'रैवतिकादिभ्यश्छः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'कौपिञ्जलहास्तिपदादण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्येदम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = 'तस्येदम्'
"सूत्रम्" = 'आथर्वणिकस्येकलोपश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''
