[[data]]
"पूर्वपदस्थितिः" = 'समस्तपदम्'
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = ''
"संज्ञा ३" = ''
"संज्ञा १" = ''
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = '''
अनेकम् अन्यपदार्थे।
द्वन्द्वतत्पुरुषयोर् उत्तरपदे नित्यसमासवचनम् (वा)'''
"उदाहरण-विग्रहः" = 'पञ्च जस् गो जस् धन जस्'
"समस्तपदम् उदाहरणम्" = '''
पञ्चगवधनः (पञ्चगोधन इति न।
 तत्पुरुषगर्भत्वाद् एव गव-इति।)'''
"अन्योदाहराणि" = ''
"विवरणम्" = '''
कदाचित् तत्पुरुषगर्भितः।
तद्धितार्थ… इत्यादिना।'''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 2
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 2
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'प्राप्तम् उदकं यं सः'
"समस्तपदम् उदाहरणम्" = 'प्राप्तोदकः ग्रामः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 3
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 3
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'पीतं क्षीरं येन सः'
"समस्तपदम् उदाहरणम्" = 'पीतक्षीरः बालः'
"अन्योदाहराणि" = 'कृतभोजनः धृतपुष्पा लिखितचित्रा'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 4
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 4
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'दत्तः पशुः यस्मै सः'
"समस्तपदम् उदाहरणम्" = 'दत्तपशुः रुद्रः'
"अन्योदाहराणि" = 'दत्तधनः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 5
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 5
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'उधृतं जलं यस्मात् सः'
"समस्तपदम् उदाहरणम्" = 'उधृतजलः कूपः'
"अन्योदाहराणि" = '[पतितपर्णः-वृक्षः निर्गतव्याघ्रम्- वनम्]'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 6
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 6
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'श्वेतं वस्त्रं यस्य सः'
"समस्तपदम् उदाहरणम्" = 'श्वेतवस्त्रः बालः'
"अन्योदाहराणि" = 'प्रसन्नवदनः निर्मलहृदयः स्मित्तवदनः लम्बोदरः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 7
"अन्यपदस्थितिः" = '१'
"संज्ञा २" = 'सामान्य समानाधिकरणम्'
"संज्ञा ३" = 7
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'वीराः पुरुषाः यस्मिन् सः'
"समस्तपदम् उदाहरणम्" = 'वीरपुरुषः ग्रामः'
"अन्योदाहराणि" = 'बहुजनम् बहुबीजम्'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'व्यधिकरणः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'चक्रं पाणौ यस्य सः'
"समस्तपदम् उदाहरणम्" = 'चक्रपाणिः'
"अन्योदाहराणि" = 'शूलपाणिः पुस्तकहस्ता दण्डहस्तः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'सङ्ख्योत्तरपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'विंशतेः समीपे ये सन्ति ते'
"समस्तपदम् उदाहरणम्" = 'उपविंशाः'
"अन्योदाहराणि" = 'उपदशाः उपनवताः अधिकसहस्राः आसन्नदशाः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'सङ्ख्योभयपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'द्वौ वा त्रयो वा'
"समस्तपदम् उदाहरणम्" = 'द्वित्राः'
"अन्योदाहराणि" = 'त्रिचतुराः पञ्चषाः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'सहपूर्वपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = 'कार्ये सहयोगः। विशेषसूत्रैः कदाचित् सह-स्थाने स।'
"सूत्रम्" = 'तेन सह तुल्ययोगे (प्रायेण)॥'
"उदाहरण-विग्रहः" = 'शिष्येण सह वर्तते यः'
"समस्तपदम् उदाहरणम्" = 'सशिष्यः सहशिष्यः'
"अन्योदाहराणि" = 'सपुत्रः सधनः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'समानपूर्वपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'समानस्य(॥) छन्दसि॥ ज्योतिर्जनपद ...॥ विभाषोदरे॥'
"उदाहरण-विग्रहः" = 'समान पक्षः यस्य सः'
"समस्तपदम् उदाहरणम्" = 'सपक्षः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'समानपूर्वपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = 'पृथक्-सूत्राणि'
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सतीर्थ्यः सब्रह्मचारी '
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'व्यतिहारलक्षणः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = 'अव्ययम् इदम्!'
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'केशेषु केशेषु गृहीत्वा इदं युद्धं प्रवृत्तम्'
"समस्तपदम् उदाहरणम्" = 'केशाकेशि'
"अन्योदाहराणि" = 'दण्डादण्डि मुष्टीमुष्टि'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष'
"संज्ञा ३" = 'दिगन्तराललक्षणः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'दक्षिणस्याः पूर्वस्याः दिशो यदन्तरालम्'
"समस्तपदम् उदाहरणम्" = 'दक्षिणपूर्वा'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'नञ् बहुव्रीहिः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = '५'
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'अविद्यमानः पुत्रः यस्य सः'
"समस्तपदम् उदाहरणम्" = 'अपुत्रः अपुत्रीकः'
"अन्योदाहराणि" = 'अधनः'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'प्रादिबहुव्रीहिः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'निर्गता कृपा यस्मात् सः'
"समस्तपदम् उदाहरणम्" = 'निष्कृपः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'निः'
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'प्रादिबहुव्रीहिः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'निर्गता मेधा यस्मात् सः'
"समस्तपदम् उदाहरणम्" = 'निर्मेधाः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'सु'
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'प्रादिबहुव्रीहिः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'शोभना मेधा यस्य सः'
"समस्तपदम् उदाहरणम्" = 'सुमेधाः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = 'दुः'
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'प्रादिबहुव्रीहिः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'दुर्गता मेधा यस्य सः'
"समस्तपदम् उदाहरणम्" = 'दुर्मेधाः'
"अन्योदाहराणि" = ''
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = ''
"संज्ञा २" = 'विशेष समानाधिकरणम्'
"संज्ञा ३" = 'उपमानपूर्वपदः'
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = ''
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = 'गजाननमिव/ गजस्येव आननं यस्य सः'
"समस्तपदम् उदाहरणम्" = 'गजाननः'
"अन्योदाहराणि" = 'चन्द्रवदना पुण्डरीकाक्ष'
"विवरणम्" = ''
"अभावोदाहरणम्" = ''

[[data]]
"पूर्वपदस्थितिः" = ''
"अन्यपदस्थितिः" = 'प्रजा, मेधा इत्यादि'
"संज्ञा २" = ''
"संज्ञा ३" = ''
"संज्ञा १" = 'समासविधानम्'
"अवधानावश्यकता" = ''
"परिणामः" = 'सकारादेशः आ-स्थाने'
"सूत्रम्" = ''
"उदाहरण-विग्रहः" = ''
"समस्तपदम् उदाहरणम्" = 'सुमेधस्, सुप्रजस्'
"अन्योदाहराणि" = ''
"विवरणम्" = 'सकार-अन्तत्वम्'
"अभावोदाहरणम्" = ''
