[[data]]
"अङ्गम्" = 'अपवादाभावे'
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = 'अणादयः'
"प्रासिद्ध्यम्" = '५'
"समूहः" = ''
"सूत्रम्" = '''
तस्यापत्यम् ।
[प्राग्दीव्यतोऽण् । …]'''
"प्रभावोदाहरणम्" = 'आश्वपतः। दैत्यः। औत्सः। स्त्रैणः। पौंस्नः। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'पौत्रप्रभृतिः प्रजा'
"परिणामः" = '१ एव अपत्यार्थकप्रत्ययः'
"प्रासिद्ध्यम्" = '५'
"समूहः" = ''
"सूत्रम्" = '''
एको गोत्रे ।
[अपत्यं पौत्रप्रभृति गोत्रम्]'''
"प्रभावोदाहरणम्" = ' गर्गस्य अपत्यं गार्गिः। गार्गेरपत्यं गार्ग्यः। तत्पुत्रो ऽपि गार्ग्यः। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
तस्यापत्यम्
यूनि अस्त्रियाम्'''
"परिणामः" = 'गोत्रप्रकृतिः + प्रत्ययः'
"प्रासिद्ध्यम्" = '४'
"समूहः" = ''
"सूत्रम्" = 'गोत्राद्यून्यस्त्रियाम् '
"प्रभावोदाहरणम्" = 'गार्ग्यस्य अपत्यं युवा गार्ग्यायणः। वात्स्यायनः। दाक्षायणः। प्लाक्षायणः। औपगविः। नाडायनिः।'
"अभावोदाहरणम्\n" = '''
अस्त्रियाम् इति किम्? दाक्षी। प्लाक्षी। 
दाक्षायनी।'''
"विवरणम्" = 'स्त्रियाम् अनियमः योगविभागात्।'

[[data]]
"अङ्गम्" = 'अत्'
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = 'इञ्'
"प्रासिद्ध्यम्" = '५'
"समूहः" = ''
"सूत्रम्" = 'अत इञ् ।'
"प्रभावोदाहरणम्" = 'दाशरथिः।'
"अभावोदाहरणम्\n" = '" कथं प्रदीयतां दाशरथाय मैथिली?" शेषविवक्षया भविष्यति। '
"विवरणम्" = ''

[[data]]
"अङ्गम्" = '''
बाहु। उपबाहु। विवाकु। शिवाकु। बटाकु। उपबिन्दु। वृक। चूडाला। मूषिका। बलाका। भगला। छगला। घ्रुवका। धुवका। सुमित्रा। दुर्मित्रा। पुष्करसत्। 
अनुहरत्। देवशर्मन्। अग्निशर्मन्। कुनामन्। सुनामन्। पञ्चन्। सप्तन्। अष्टन्। उदञ्चु। शिरस्। शराविन्। क्षेमवृद्धिन्। शृङ्खलातोदिन्। खरनादिन्। 
नगरमर्दिन्। प्राकारमर्दिन्। लोमन्। अजीगर्त। कृष्ण। सलक। युधिष्ठिर। अर्जुन। साम्ब। गद। प्रद्युम्न। राम। उदङ्कः संज्ञायाम्।'''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = 'इञ्'
"प्रासिद्ध्यम्" = '२'
"समूहः" = ''
"सूत्रम्" = 'बाह्वादिभ्यश्च ।'
"प्रभावोदाहरणम्" = 'बाहविः। औपबाहविः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'अमितौजस् अम्भस् अम्भूयस्'
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = 'इञ्, सलोपः'
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = ' अमितौजसः सलोपश्च।  (गणसूत्रम्)। अम्भूयो ऽम्भसोः सलोपश्च'
"प्रभावोदाहरणम्" = 'बाहुर्नाम कश्चित्, तस्य अपत्यं बाहवः। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'बाह्वादिः गोत्रभावे लोकेऽदृष्टाः'
"प्रत्ययः/ विवक्षा" = '''
तस्यापत्यम्
'''
"परिणामः" = '-इञ्'
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'बाह्वादिप्रभृतिषु येषां दर्शनं गोत्रभावे लौकिके ततो ऽन्यत्र तेषां प्रतिषेधः। '
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '''
तस्यापत्यम्
'''
"परिणामः" = '-इञ्'
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'सम्बन्धिशब्दानां च तत्सदृशात् प्रतिषेधः।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'सुधातुरकङ् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'गोत्रे कुञ्जादिभ्यश्च्फञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'नडादिभ्यः फक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'हरितादिभ्योऽञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'यञिञोश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'शरद्वच्छुनकदर्भाद्भृगुवत्साग्रायणेषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'द्रोणपर्वतजीवन्तादन्यतरयाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अनृष्यानन्तर्ये बिदादिभ्योऽञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'गर्गादिभ्यो यञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'मधुबभ्र्वोर्ब्राह्मणकौशिकयोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कपिबोधादाङ्गिरसे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'वतण्डाच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'लुक् स्त्रियाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अश्वादिभ्यः फञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'भर्गात्‌ त्रैगर्ते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'शिवादिभ्योऽण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अवृद्धाभ्यो नदीमानुषीभ्यस्तन्नामिकाभ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'ऋष्यन्धकवृष्णिकुरुभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'मातुरुत्‌ संख्यासम्भद्रपूर्वायाः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कन्यायाः कनीन च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'विकर्णशुङ्गच्छगलाद्वत्सभरद्वाजात्रिषु ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'पीलाया वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = '१'
"समूहः" = ''
"सूत्रम्" = 'ढक् च मण्डूकात्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'स्त्रीः'
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = '५'
"समूहः" = ''
"सूत्रम्" = 'स्त्रीभ्यो ढक् ।'
"प्रभावोदाहरणम्" = 'कौन्तेयः'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'द्व्यचः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'इतश्चानिञः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'शुभ्रादिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'विकर्णकुषीतकात्‌ काश्यपे ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'भ्रुवो वुक् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कल्याण्यादीनामिनङ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कुलटाया वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'चटकाया ऐरक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'गोधाया ढ्रक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'आरगुदीचाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'क्षुद्राभ्यो वा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'पितृष्वसुश्छण् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'ढकि लोपः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'मातृष्वसुश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'चतुष्पाद्भ्यो ढञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'गृष्ट्यादिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'राजश्वशुराद्यत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'क्षत्राद्घः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कुलात्‌ खः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अपूर्वपदादन्यतरस्यां यड्ढकञौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'महाकुलादञ्खञौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'दुष्कुलाड्ढक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'स्वसुश्छः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'भ्रातुर्व्यच्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'व्यन् सपत्ने ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'रेवत्यादिभ्यष्ठक् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'गोत्रस्त्रियाः कुत्सने ण च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'वृद्धाट्ठक् सौवीरेषु बहुलम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'फेश्छ च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'फाण्टाहृतिमिमताभ्यां णफिञौ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कुर्वादिभ्यो ण्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'सेनान्तलक्षणकारिभ्यश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'उदीचामिञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'तिकादिभ्यः फिञ् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'कौसल्यकार्मार्याभ्यां च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अणो द्व्यचः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'उदीचां वृद्धादगोत्रात्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'वाकिनादीनां कुक् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'पुत्रान्तादन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'प्राचामवृद्धात्‌ फिन् बहुलम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'तस्यापत्यम्'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'मनोर्जातावञ्यतौ षुक् च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = '‌गोत्रम्‌'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'अपत्यं पौत्रप्रभृति गोत्रम्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'युवा'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'जीवति तु वंश्ये युवा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'युवा'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'भ्रातरि च ज्यायसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = 'युवा'
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'वाऽन्यस्मिन् सपिण्डे स्थविरतरे जीवति ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'वृद्धस्य च पूजायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"समूहः" = ''
"सूत्रम्" = 'यूनश्च कुत्सायाम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''
