[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'प्राग्दिशो विभक्तिः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'किंसर्वनामबहुभ्योऽद्व्यादिभ्यः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इदम इश् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'एतेतौ रथोः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'एतदोऽश् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सर्वस्य सोऽन्यतरस्यां दि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'किंसर्वनामबहुभ्यः'
"प्रत्ययः/ विवक्षा" = '५'
"परिणामः" = 'तसिल्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'पञ्चम्यास्तसिल् ।'
"प्रभावोदाहरणम्" = '''
कुतः। यतः। ततः। बहुतः।
'''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = 'पूर्वस्वरस्योदात्तत्वं सूचयति लित्।'

[[data]]
"अङ्गम्" = 'किंसर्वनामबहुभ्यः'
"प्रत्ययः/ विवक्षा" = 'तसि'
"परिणामः" = 'तसिल्'
"प्रासिद्ध्यम्" = '२'
"सूत्रम्" = 'तसेश्च ।'
"प्रभावोदाहरणम्" = 'यतः। ततः। बहुत आगतः। '
"अभावोदाहरणम्\n" = ''
"विवरणम्" = 'तसेस् तसिल्वचनं स्वरार्थं विभक्त्यर्थं च।'

[[data]]
"अङ्गम्" = '''
परि अभि इत्येताभ्यां
सर्वोभयार्थाभ्यामेव'''
"प्रत्ययः/ विवक्षा" = '५'
"परिणामः" = 'तसिल्'
"प्रासिद्ध्यम्" = '३'
"सूत्रम्" = '''
पर्यभिभ्यां च ।
सर्वोभयार्थाभ्यामेव (वार्तिकम्) ॥'''
"प्रभावोदाहरणम्" = 'परितः। सर्वतः इत्यर्थः। अभितः। उभयतः इत्यर्थः।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'किंसर्वनामबहुभ्यः'
"प्रत्ययः/ विवक्षा" = '७'
"परिणामः" = 'त्रल्'
"प्रासिद्ध्यम्" = '५'
"सूत्रम्" = 'सप्तम्यास्त्रल् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इदमो हः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'किमोऽत्‌ ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'वा ह च च्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इतराभ्योऽपि दृश्यन्ते ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सर्वैकान्यकिंयत्तदः काले दा ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इदमो र्हिल् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अधुना ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'दानीं च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तदो दा च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'तयोर्दार्हिलौ च च्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'अनद्यतने र्हिलन्यतरस्याम् ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'सद्यःपरुत्परार्यैषमःपरेद्यव्यद्यपूर्वेद्युरन्येद्युरन्यतरेद्युरितरेद्युरपरेद्युरधरेद्युरुभयेद्युरुत्तरेद्युः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = 'किंसर्वनामबहुभ्यो ऽद्व्यादिभ्यः'
"प्रत्ययः/ विवक्षा" = 'प्रकारः'
"परिणामः" = 'थाल्'
"प्रासिद्ध्यम्" = '४'
"सूत्रम्" = 'प्रकारवचने थाल् ।'
"प्रभावोदाहरणम्" = 'यथा। सर्वथा।'
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'इदमस्थमुः ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'किमश्च ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''

[[data]]
"अङ्गम्" = ''
"प्रत्ययः/ विवक्षा" = ''
"परिणामः" = ''
"प्रासिद्ध्यम्" = ''
"सूत्रम्" = 'था हेतौ च च्छन्दसि ।'
"प्रभावोदाहरणम्" = ''
"अभावोदाहरणम्\n" = ''
"विवरणम्" = ''
