[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'र्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'लोपः, पूर्वतन-अणः दीर्घः'
"विधिप्रकारः" = 'रलोपः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
 रो रि (लोपः) (८।३।१४)
ढ्रलोपे पूर्वस्य दीर्घोऽणः (६।३।१११)'''
"उदाहरणम्" = 'पुना रमते'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खर् -कखपफ'
"परवर्णस्थितिः" = 'न शर्-परः'
"परिणामः" = 'स्'
"विधिप्रकारः" = 'रेफस्थ-विसर्जनीयादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः
[ विसर्जनीयस्य सः (खरि)
शपरे खरि विसर्जनीयस्य विसर्जनीयः ।]'''
"उदाहरणम्" = '''
विष्णुः + त्राता = विष्णुस्त्राता।
हरिः +त्सरुः = हरिः त्सरुः'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = '''
क् प् ख् फ्
इत्यत्र अपवादः उक्तः'''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खर् -कखपफ'
"परवर्णस्थितिः" = 'शर्-परः'
"परिणामः" = 'लोपः'
"विधिप्रकारः" = 'रेफस्थ-विसर्जनीयादेशः'
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः
[ शपरे खरि विसर्जनीयस्य विसर्जनीयः ।
खर्परे शरि वा विसर्गलोपो वक्तव्यः (वा)]'''
"उदाहरणम्" = 'हरिः +त्सरुः = हरिः त्सरुः/ हरि त्सरुः'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = '''
क् प् ख् फ्
इत्यत्र अपवादः उक्तः'''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख्'
"परवर्णस्थितिः" = 'न क्ष् परवर्णः ।'
"परिणामः" = 'ೱ'
"विधिप्रकारः" = 'रेफस्थ-विसर्जनीयादेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
[खरवसासनयोर्विसर्जनीयः]
कुप्वो ^क ^पौ च'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'रेफस्थ-विसर्जनीयादेशः'
"विधिः" = ''
"सूत्रम्" = 'रोः सुपि ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
भो,भगो,अघो +
अ / आ + '''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अश्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'य्/ लोपः'
"विधिप्रकारः" = 'विसर्ग'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
[ससजुषो रुः (८.२.६६) ]
भोभगोअघोअपूर्वस्य योऽशि।
व्योर्लघुप्रयत्नतरः शाकटायनस्य ।
[लोपः शाकल्यस्य (अशि परे पदस्य) (पूर्वत्रासिद्धम्)।
हलि सर्वेषाम् (लोपः)। (८।३।२२)]'''
"उदाहरणम्" = '''
गजा इह।
राम एति। बाल आगच्छति।
न रेफान्ताव्यये - प्रातर् इच्छति इत्येव।'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खर्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'विसर्जनीयस्य सः ।'
"उदाहरणम्" = 'रामश्चिनोति / रामश्छदति / रामष्टीकते / रामष्ठकारीयते / रामस्तरति / रामस्थूर्वति'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'खर् शर्परः'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ः'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'शर्परे विसर्जनीयः ।  रामः क्षत्रियः → रामः क्षत्रियः । '
"उदाहरणम्" = 'कः त्सरुः → कः त्सरुः । '
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श् ष् स्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'स् / ः'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
[खरवसासनयोर्विसर्जनीयः]
वा शरि (विसर्जनीयस्य विसर्जनीयः)
[ स्तोः श्चुनाश् चुः। ष्टुना ष्टुः ।]'''
"उदाहरणम्" = '''
हरिः षष्ठः → हरिःषष्ठः, हरिष्षष्ठः ।
हरिः शेते → हरिःशेते, हरिश्शेते । '''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = '{श् ष् स्} +‌खर्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'स् / ः/-'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'लोपः पूर्वस्य'
"सूत्रम्" = '''
वा शरि (विसर्जनीयस्य विसर्जनीयः)
खर्परे शरि वा विसर्गलोपो वक्तव्यः'''
"उदाहरणम्" = ' रामः स्थाता → रामः स्थाता, रामस् स्थाता, राम स्थाता ।'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'सम्, पुम् , कान्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'श् ष् स्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'स्'
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = 'सम्पुंकानां सो वक्तव्यः'
"उदाहरणम्" = '''
सम् + सुट् + कर्तृ [सम्परिभ्यां करोतौ भूषणे] = सं+स्क = सँस्स्कर्तृ / संस्स्कर्तृ
पुम् + कोकिलः = पुँस्कोकिलः / पुंस्कोकिलः 
कान् कान् → काँस्कान्, कांस्कान्'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'प् फ्'
"परवर्णस्थितिः" = 'न प्स् परवर्णः ।'
"परिणामः" = 'ೲ'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः
कुप्वो ^क ^पौ च'''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'अनव्ययः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख् प्'
"परवर्णस्थितिः" = '''
न क्ष् परवर्णः।
न काम्यच्।'''
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्गसन्धिः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
[खरवसासनयोर्विसर्जनीयः]
सोऽअपदादौ।
अनव्ययस्य (वा)'''
"उदाहरणम्" = '''
यशस्कम्। काम्यच् पयस्काम्यति।
 इह मा भूत्, प्रातः कल्पम्, पुनः कल्पम्।'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'अनव्ययः'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख् प्'
"परवर्णस्थितिः" = '''

काम्यच्।'''
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्गसन्धिः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः। सोऽपदादौ। अनव्ययस्य (वा)
काम्ये रोरेवेति वाच्यम्।'''
"उदाहरणम्" = '''

 इह म भूत्, गीः काम्यति। धूः काम्यति।'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'अनव्ययः इ/उ अन्ते'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख् प्'
"परवर्णस्थितिः" = '''
न क्ष् परवर्णः।
न काम्यच्।'''
"परिणामः" = 'ष्'
"विधिप्रकारः" = 'विसर्गसन्धिः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः
सोऽअपदादौ।
अनव्ययस्य (वा) इणः षः॥'''
"उदाहरणम्" = 'यजुष्कल्पम्। क सर्पिष्कम्। यजुष्कम्।'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'अनव्ययः इ/उ अन्ते'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख् प्'
"परवर्णस्थितिः" = '''

काम्यच्।'''
"परिणामः" = 'ष्'
"विधिप्रकारः" = 'विसर्गसन्धिः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
खरवसासनयोर्विसर्जनीयः। सोऽपदादौ। अनव्ययस्य (वा)
काम्ये रोरेवेति वाच्यम्। इणः षः॥'''
"उदाहरणम्" = 'काम्य सर्पिष्काम्यति'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
इ/ उ (न मुहुः/ कस्कादिगणः)
/ नमस् (गतिसंज्ञायां) / पुरस्'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् प् ख् फ्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ष्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः'
"सूत्रम्" = '''
नमस्-पुरसोः गत्योः (षः)।
इदुदुपधस्य चाप्रत्ययस्य  कुप्वोः सोऽपदादौ॥'''
"उदाहरणम्" = '''
नमस्कर्ता। 
भ्रातुष्पुत्रः।
गत्योः इति किम्? पूः, पुरौ, पुरः करोति।'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'तिरस्'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् ख्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = 'तिरसोर् अन्यतरस्याम्'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'द्विस्/त्रिस्'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् प् ख् फ्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ष्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = 'द्विस्त्रिश्चतुरिति कृत्वोऽर्थे अन्यतरस्याम्॥'
"उदाहरणम्" = '''
द्विष्करोति, द्विः करोति।
'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'न समासे'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'इस्/ उस्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् प् ख् फ्'
"परवर्णस्थितिः" = 'सामर्थ्ये पूर्वपदेन सह'
"परिणामः" = 'ष् वा'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य विकल्पेन'
"सूत्रम्" = '''
इसुसोः सामर्थ्ये अन्यतरस्याम्। 
[नित्यं समासे अनुत्तरपदस्थस्य।]'''
"उदाहरणम्" = 'सर्पिष्करोति, सर्पिः करोति यजुस्करोति, यजुः करोति। सामर्थ्ये इति किम्? तिष्ठतु सर्पिः, पिव त्वमुदकम्।'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'समासे'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'इस्/ उस्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् प् ख् फ्'
"परवर्णस्थितिः" = 'सामर्थ्ये पूर्वपदेन सह'
"परिणामः" = 'ष्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'नित्यं समासेऽनुत्तरपदस्थस्य ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'समासे अ +'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स् ः'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'क् प् ख् फ्'
"परवर्णस्थितिः" = 'कृ कमि कंस कुम्भ पात्र कुशा कर्णी'
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
अतः कृकमिकंस-कुम्भ-पात्रकुशाकर्णीष्व-नव्ययस्य 
(नित्यं समासे ऽनुत्तरपदस्य)'''
"उदाहरणम्" = '''
प्रातःकल्पम्।
अयस्कारः।'''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'अधःशिरसी पदे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'कस्कादिषु च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'छन्दसि वाऽप्राम्रेडितयोः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'कःकरत्करतिकृधिकृतेष्वनदितेः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'पञ्चम्याः परावध्यर्थे ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'पातौ च बहुलम् ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = 'स्'
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'षष्ठ्याः पतिपुत्रपृष्ठपारपदपयस्पोषेषु ।'
"उदाहरणम्" = 'बृहस्पतिः, मनसस्पतिः'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'विसर्जनीयस्य आदेशः'
"विधिः" = ''
"सूत्रम्" = 'इडाया वा ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = ''
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = ''
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = ''
"विधिः" = ''
"सूत्रम्" = '[अन्यसूत्राणि]'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स् सजुष्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते अपवादाभावे'
"परवर्णस्थितिः" = ''
"परिणामः" = 'रुँ'
"विधिप्रकारः" = ''
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = 'ससजुषो रुः पदस्य (८।२।६६)'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = 'अ +'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = '''
अ
हश्'''
"परवर्णस्थितिः" = ''
"परिणामः" = 'उ'
"विधिप्रकारः" = 'विसर्ग'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
ससजुषो रुः पदस्य (८.२.६६) 
[अतो रोरप्लुतादप्लुते। हशि च (उत्)।
एङः पदान्तादति (अतः लोपः)]'''
"उदाहरणम्" = 'रामोऽपि।'
"अभावोदाहरणम्" = 'रोरित्युकारानुबन्धग्रहणान्नेह । प्रातरत्र । भ्रातर्गच्छ । '
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '^ अ/आ'
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'र्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'लोपः, पूर्वतन-अणः दीर्घः'
"विधिप्रकारः" = 'विसर्ग'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
ससजुषो रुः
[ रो रि (लोपः) (८।३।१४)
ढ्रलोपे पूर्वस्य दीर्घोऽणः (६।३।१११)]'''
"उदाहरणम्" = 'हरी रमते'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अवसानम्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'ः'
"विधिप्रकारः" = 'विसर्ग'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
ससजुषो रुः (८.२.६६) 
[खरवसासनयोर्विसर्जनीयः]'''
"उदाहरणम्" = 'श्रीधरस् षष्ठः - श्रीधरर् षष्ठः - श्रीधरः षष्ठः- …'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = '''
इच् +
ऋकारान्तशब्द-संबोधनरूपे वा'''
"पूर्वाक्षरम् सन्धिपूर्वम्" = 'र् स्'
"उत्तराक्षरम् सन्धिपूर्वम्" = 'अश् - र्'
"परवर्णस्थितिः" = ''
"परिणामः" = 'र्'
"विधिप्रकारः" = 'विसर्ग'
"विधिः" = 'आदेशः पूर्वस्य'
"सूत्रम्" = '''
ससजुषो रुः (८.२.६६) 
'''
"उदाहरणम्" = 'हरिर् अतः।'
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'पदान्तस्य रुत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अवयाःश्वेतवाःपुरोडाश्च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'पदान्तस्य रुत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अहन् ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'पदान्तस्य रुत्वम्'
"विधिः" = ''
"सूत्रम्" = 'रोऽसुपि ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'पदान्तस्य रुत्वम्'
"विधिः" = ''
"सूत्रम्" = 'अम्नरूधरवरित्युभयथा छन्दसि ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = 'पदान्तस्य रुत्वम्'
"विधिः" = ''
"सूत्रम्" = 'भुवश्च महाव्याहृतेः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = '''
पदान्तस्य दत्वम् 
रुत्वम् च'''
"विधिः" = ''
"सूत्रम्" = 'वसुस्रंसुध्वंस्वनडुहां दः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = '''
पदान्तस्य दत्वम् 
रुत्वम् च'''
"विधिः" = ''
"सूत्रम्" = 'तिप्यनस्तेः ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = '''
पदान्तस्य दत्वम् 
रुत्वम् च'''
"विधिः" = ''
"सूत्रम्" = 'सिपि धातो रुर्वा ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''

[[data]]
"पूर्वाक्षरस्थितिः" = ''
"पूर्वाक्षरम् सन्धिपूर्वम्" = ''
"उत्तराक्षरम् सन्धिपूर्वम्" = 'पदान्ते'
"परवर्णस्थितिः" = ''
"परिणामः" = ''
"विधिप्रकारः" = '''
पदान्तस्य दत्वम् 
रुत्वम् च'''
"विधिः" = ''
"सूत्रम्" = 'दश्च ।'
"उदाहरणम्" = ''
"अभावोदाहरणम्" = ''
"पश्चात्तनक्रिया" = ''
"विवरणम्" = ''
